cli/cmd/cluster-install.go

To skip component installation. This is useful if users want to do some
operations in the cluster before installing components.

cli/install: add skip-components flag

---

ci/packet/packet-cluster.lokocfg.envsubst
test/components/flatcar-linux-update-operator/fluo_test.go

This reverts commit cc303e7aa822a9320566fa530726101fd0394cea.
The CI disables reboots on controller nodes now, so we should be able to
test FLUO again on Packet.

Revert "ci/packet: disable installing and testing FLUO"

---

pkg/util/walkers/copying.go
pkg/util/walkers/copying_test.go

To avoid leaving old content untouched when updating files, which may
happen if new content is smaller than the old one.
Closes #40

CopyWalker: truncate file when writing

---

pkg/components/metallb/component.go

We took this from upstream but running speaker Pods on the master node
it doesn't make much sense since they're not likely to host services
accessible by the outside.
Fixes #46

metallb: make sure controllers run on controllers and speakers run on workers

---

Makefile

As CI will merge the PR code into master branch when running tests, so
then local (CI) master branch diff will always be empty, so we should
compare against actual reference of the remote master branch, which can
be taken from metadata files provided by concourse.
From https://github.com/telia-oss/github-pr-resource:
>Clones the base (e.g. master branch) at the latest commit, and merges the pull request at the specified commit into master. This ensures that we are both testing and setting status on the exact commit that was requested in input. Because the base of the PR is not locked to a specific commit in versions emitted from check, a fresh get will always use the latest commit in master and report the SHA of said commit in the …

Makefile: use concourse base_sha if available when linting

---

Makefile

This commit adds 'build-test' target to Makefile, which will compile all
tests code, without running them, to make sure that syntax for all
tests, including e2e tests is correct. This is useful while refactoring.
It also adds 'all' target, which combines all possible checks for the
code into a single target to run, which should be run to run all
possible checks for the code.
Closes #93 #44

Makefile: add 'all' and 'build-test' targets

---

pkg/config/config.go
pkg/k8sutil/create.go
pkg/terraform/executor.go

Even though we don't use it right now, since Go 1.13 it's recommended to use `%w` with combination of `fmt.Errorf`, so then receiver can unwrap underlying error.

Fix error wrapping across packages

---

pkg/platform/aws/aws.go
pkg/platform/aws/template.go

And only render values, which are actually defined. With this patch,
more defaults from Terraform are used, so it is easier to change those
defaults in the future.
This commit also reduces amount of Terraform configuration which is
generated, which should make debugging easier.

pkg/install/aws: use defaults from Terraform

---

pkg/terraform/executor.go
pkg/terraform/executor_test.go

So it's easier to debug which key is wrong.

pkg/terraform/executor.go: include key in Output error message

---

pkg/components/metallb/component.go
pkg/components/metallb/manifests.go

* Also I forgot to install the dashboard in previous PR. Now that is taken care of in 1st commit.
* Dashboard looks like this: https://snapshot.raintank.io/dashboard/snapshot/VSd2fULu673q1fuNr4TF5t9MtgD7C90v

metallb-dashboard: Add error and updates monitoring

---

Makefile

They are not so critical and unfortunately the defaults disable e.g.
catching missing documentation for exported functions and structs.
Refs https://github.com/golangci/golangci-lint/issues/928

Makefile: disable default excludes when running linter

---

cli/cmd/cluster-destroy.go
cli/cmd/cluster-install.go
cli/cmd/cluster.go
docs/cli/lokoctl_cluster_destroy.md
docs/cli/lokoctl_cluster_install.md
docs/installer/general.md
pkg/terraform/config.go
pkg/terraform/executor.go
pkg/terraform/executor_test.go

So we don't show Terraform output by default.
Also, add more logging to show the execution phases and fix a bug where "terraform plan" was not showing the diff if `--verbose` is false, check commit messages for details.
Closes #129

 *: change quiet flag to verbose and disable it by default 

---

Makefile
cli/cmd/cluster-install.go

We're using global variables heavily for CLI handling so it doesn't make
sense to have this linter.

lint: disable gochecknoglobals linter

---

Makefile

There are ton of cases where the linter can't run, with errors like:
WARN [runner] Can't run linter goanalysis_metalinter: assign: failed prerequisites: inspect@github.com/kinvolk/lokomotive/pkg/platform/packet
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [lokomotive/pkg/platform/packet/packet.go:271:20: cannot use arguments (variable of type []string) as string value in argument to ex.Execute]
ERRO Running error: buildssa: analysis skipped: errors in package: [lokomotive/pkg/platform/packet/packet.go:271:20: cannot use arguments (variable of type []string) as string value in argument to ex.Execute]
The error is not crystal clear, but if you look closely it says there
were some errors in the package. While not very clear, that seems to
mean …

Makefile: Only run linter if code compiles

---

pkg/platform/packet/packet.go
pkg/platform/packet/template.go

This patches are extracted from https://github.com/kinvolk/lokomotive/pull/119. I found a bug in the code that I needed to change for that PR, so I fixed it.
That PR is not yet ready to be merged, so I'm including the fixes I found while writing it in this PR. Most of the commits are cosmetic (create a function for this and that) and make way more sense when PR #119 is merged, as those functions will not be so simple. To keep the backport simple, I decided to include them here, though
The fix is in patch: `packet: Use user-specified pool name for TF pool`, all the rest are cleanups or cosmetic changes. I c&p here the commit message from that patch, as it explains quite well what is doing and why it is important (let me know if I'm missing something!):
Before this commit, the pool name …

packet: Use user-specified pool name for TF pool

---

pkg/platform/packet/template.go

Otherwise we'll be using the same as the controller module.

packet: use worker pool variable for the IPXE script URL

---

docs/configuration-reference/platforms/packet.md

Ported from
https://github.com/kinvolk/lokomotive-kubernetes/blob/master/docs/flatcar-linux/packet.md#arm-support-and-hybrid-clusters
and removing unnecessary details.

docs/packet: add ARM/x86 hybrid cluster instructions

---

cli/cmd/cluster-apply.go

This commit fixes a regression introduced in
485994b8baef25a8b2abeb2731fd659e6c35a34c, which causes, that 'cluster
apply' command can no longer install components.
This is happening, because it changed the way we initialize the
componentsToApply variable. Before it was a nil slice and mentioned
commit changed it to initialize it as an slice with number of empty
elements equal to number of configured components. As we use 'append'
later, we end up with N empty elements and N valid elements, hence the
components installation fails.
This commit changes an initialation to simply assignment, which is a
most common approach for working with slices in Go, together with
'append'. We don't need to use 'make' for optimization here.
Closes #160

cli/cmd/cluster-apply.go: initialize components to apply as empty slice

---

Makefile
test/components/kubernetes/kubelet_disruptive_test.go

This commit changes the build tag as follows:
`s | disruptive-e2e | disruptivee2e | g`
Having hypen in the build tag excludes the file from being built.

test-e2e: Fix the build tag name

---

ci/aws/aws-cluster.lokocfg.envsubst
docs/configuration-reference/platforms/aws.md
examples/aws-production/cluster.lokocfg
examples/aws-testing/cluster.lokocfg
pkg/platform/aws/aws.go
pkg/platform/aws/template.go

This facility is available in lokomotive-kubernetes
With this PR , a user can create worker pools in AWS as well (#155 )
This also removes the worker related configuration fields such as `worker_count` , `worker_type` etc. from the config struct and moves them into workerpool struct. Fixes #156 
This makes creating the worker pool mandatory to add workers for creating a Lokomotive cluster.

Add ability to create AWS worker pools

---

ci/aws/aws-cluster.lokocfg.envsubst

We're currently using t3.medium instances which cost $0.048 per hour.
Let's try to use spot instances with $0.02 as target price.
According to https://aws.amazon.com/ec2/spot/pricing/ the spot price for
a t3.medium is $0.0144 but even if we get a worse instance tests will
probably be ok.
We should revisit this when we enable single-node Lokomotive update
testing since that requires more memory.
Closes #149

ci: use spot instances for AWS testing

---

ci/aws/aws-cluster.lokocfg.envsubst

- This commit fixes the condition where all AWS CI jobs have the same
worker pool name, causing errors such as:
```
error: Error creating LB Target Group: DuplicateTargetGroupName: A
target group with the same name 'pool-ci-workers-http' exists, but
with different settings
```

fix: Prefix cluster name to aws worker pool

---

examples/aws-production/cluster.lokocfg
examples/aws-testing/cluster.lokocfg
pkg/platform/aws/aws.go

There are tight restrictions on resource name length on AWS. Check
cluster name and worker pool name against those.
Fixes #179

pkg/aws: check cluster name and worker pool name length

---

ci/packet-arm/packet-arm-cluster.lokocfg.envsubst
docs/configuration-reference/platforms/packet.md

Point to the iPXE file that is generated as Flatcar
release output and uses relative URLs to refer to
the kernel and image.

Packet: Use iPXE file from the Flatcar release site

---

test/monitoring/control-plane_test.go
test/monitoring/monitoring_test.go

* Create a prometheus client only once and then pass it to the tests that need it.
* This refactor will be consumed in #120 and #140

refactor prometheus test code

---

docs/configuration-reference/backend/s3.md

This is not trivial and only documented in the terraform s3 backend type
documentation AFAIK:
https://www.terraform.io/docs/backends/types/s3.html#dynamodb_table

docs/backend/s3: add primary key requirement to dynamodb table

---

ci/aws/aws-cluster.lokocfg.envsubst
ci/packet/packet-cluster.lokocfg.envsubst
docs/configuration-reference/components/external-dns.md
pkg/components/external-dns/component.go
pkg/components/external-dns/component_test.go

We were setting it to the AWS DNS Zone ID and that means that several
clusters using the same DNS Zone will interact badly with each other.
This exposes it to the user so they can choose a reasonable ID.

components/external-dns: expose owner_id

---

docs/configuration-reference/components/prometheus-operator.md

The current sentence is ambiguous: it might be interpreted as the file
needing to use 2 spaces as indentation.
Change it to clarify the whole file needs to be indented two spaces.

docs/prometheus-operator: clarify alertmanager config indentation

---

test/components/cert-manager/cert-manager_test.go
test/components/cluster-autoscaler/cluster-autoscaler_test.go
test/components/contour/contour_test.go
test/components/coredns/coredns_test.go
test/components/dex/dex_test.go
test/components/external-dns/external-dns_test.go
test/components/flatcar-linux-update-operator/fluo_test.go
test/components/gangway/gangway_test.go
test/components/httpbin/httpbin_test.go
test/components/kubernetes/controller-manager_test.go
test/components/kubernetes/kubelet_disruptive_test.go
test/components/kubernetes/kubelet_test.go
test/components/metallb/metallb_test.go
test/components/metrics-server/metrics_server_test.go
test/components/openebs-operator/openebs_operator_test.go
test/components/prometheus-operator/prometheus_operator_test.go
test/components/rook/rook_test.go
test/components/util/util.go

As this is an anti-pattern when writing tests in Go. When helper
function takes testing.T as an argument and errors occurs, t.Fatalf or
t.Errorf should be used instead of returning error.

test/components/util: don't return errors when taking testing.T as arg

---

docs/concepts/securing-lokomotive-cluster.md
docs/quickstarts/aws.md
docs/quickstarts/baremetal.md
docs/quickstarts/packet.md

By default the cluster will refuse to run most images because they run
as root and that's disallowed by the PodSecurityPolicy. Mention this in
the quickstart pointing to the relevant documentation.
Also, link to the Kubernetes Basics documentation so inexperienced users
can learn about Kubernetes usage.
Reported-by: @jpetazzo

docs/quickstarts: add reference to usage docs and PSP note

---

pkg/components/metallb/component.go
pkg/components/metallb/manifests.go
test/monitoring/components_alerts_test.go
test/monitoring/monitoring_test.go

This commit adds a prometheus operator CR PrometheusRule which includes
alertmanager rules for metallb.
* This sends an alert when it sees that a session is not established for
more than 2mins.
* This sends an alert when any of the pods have stale config.
Signed-off-by: Suraj Deshmukh <suraj@kinvolk.io>

metallb: Add alerts for metallb

---

test/monitoring/scrape_targets_test.go

Add check to the tabwriter object before flushing. It is possible that
test fails and the object was never initialised, hence this can cause
unnecessary panic in the test run.

monitoring scrape test: Don't flush if nil object

---

cli/cmd/component-delete.go
cli/cmd/root.go
cli/cmd/utils.go
docs/cli/lokoctl_component.md
docs/cli/lokoctl_component_delete.md
pkg/components/cert-manager/component.go
pkg/components/cluster-autoscaler/component.go
pkg/components/contour/component.go
pkg/components/dex/component.go
pkg/components/external-dns/component.go
pkg/components/flatcar-linux-update-operator/component.go
pkg/components/gangway/component.go
pkg/components/httpbin/component.go
pkg/components/metadata.go
pkg/components/metallb/component.go
pkg/components/metrics-server/component.go
pkg/components/openebs-operator/component.go
pkg/components/openebs-storage-class/component.go
pkg/components/prometheus-operator/component.go
pkg/components/rook-ceph/component.go
pkg/components/rook/component.go
pkg/components/util/doc.go
pkg/components/velero/velero.go

**NOTE**: For detailed information, see changes per commit.
Fixes #67

Add support for `lokoctl component delete`

---

docs/quickstarts/aws.md
docs/quickstarts/baremetal.md
docs/quickstarts/packet.md

Fixes: https://github.com/kinvolk/lokomotive/issues/248

quickstart-docs: Add ssh-agent instructions

---

pkg/platform/packet/packet.go

Creating workers at the same time than the controllers only saves time
if the cluster is small. If you have more than 3 workers, this won't
save much time. Also, it will increase a lot the time the user will wait
to answer the next prompt.
This patch just creates the controllers and asks the user ASAP for the
next input. This way, the user needs to wait for manual steps as little
as possible.
This may increase the total time it takes to create the cluster, but
reduces the time the user needs to different stages and do manual
actions.

packet: Remove optimization to create workers

---

Makefile

The ".git/resource/base_sha" file exists in the concourse CI only. When
running it locally, the code fallbacks to "master". However, there is no
guarantee that the master branch in a local coputer is up to date.
This patch just changes the fallback to be "origin/master", as that has
more chances of being up to date. For example, I usually work in
branches and rarely update my master branch.
Using "origin/master" will also continue to work on users that update
the local master branch, as when they do so, they update the
"origin/master" reference too, usually.
The downside is that it assumes that the remote is named "origin". This
is a reasonable requirement for local development, however, as many
other project have them. If you want to name it differently, you can run
the linter manually …

Makefile: lint: Fallback to "origin/master"

---

Makefile

Currently, when running "make build-test" it shows 157 of non useful
information, like:
```
testing: warning: no tests to run
PASS
coverage: [no statements]
ok  	github.com/kinvolk/lokomotive/test/components/prometheus-operator	(cached)	coverage: [no statements] [no tests to run]
testing: warning: no tests to run
PASS
coverage: [no statements]
ok  	github.com/kinvolk/lokomotive/test/components/rook	(cached)	coverage: [no statements] [no tests to run]
?   	github.com/kinvolk/lokomotive/test/components/util	[no test files]
testing: warning: no tests to run
```
If there is a compilation error, it is printed to stderr. Therefore,
just supressing stdout is fine. Removing the "-v" option doesn't help
either, as still tons of lines are printed and it says that no test were
run.
Also, some other …

Makefile: Supress stdout when building tests

---

pkg/terraform/executor.go

When user is using lokoctl cluster apply/destroy in normal mode (not verbose) then show users what went wrong by showing last 20 lines of the logs.
And also let user know where the log file resides.
Fixes #225

Show logs when terraform fails in `lokoctl cluster apply/destroy` 

---

docs/configuration-reference/components/rook-ceph.md
pkg/components/rook-ceph/component.go
pkg/components/rook-ceph/manifests.go

**NOTE**: To review this PR, please see the changes per commit.
Fixes: https://github.com/kinvolk/lokomotive/issues/381

rook-ceph: Add StorageClass config

---

docs/CONTRIBUTING.md

This commits adds some guidelines that I believe will help to review PRs
and simplify the PR creation process, that is currently a little more
chaotic than it could be.
Hopefully PRs will be merged faster if they are easier to review too.

docs: Add detailed contributing guidelines

---

pkg/components/contour/component_test.go
pkg/components/contour/manifest.go

Fixes #416 
Rendering of `ingress_hosts` field in values template results in a space delimited list of strings.
```
ingress_hosts: [ test.local cluster.local]
```
This causes error in rendering of helm chart [envoy service template], and also results in an error when wildcard pattern is used in `ingress_hosts`.

Fix rendering of `ingress_hosts` in Contour component

---

Makefile

It is latest version available now.

Makefile: update golangci-lint to 1.27.0

---

Makefile

We aren't aligned on a single approach regarding adding info to
Go errors. Since we seem to be using `fmt.Errorf` more than other
approaches (e.g. wrapping), we should disable this check for now.

Makefile: Disable goerr113 linter check

---

ci/aks/aks-cluster.lokocfg.envsubst
ci/aws/aws-cluster.lokocfg.envsubst
ci/packet/packet-cluster.lokocfg.envsubst
docs/configuration-reference/components/prometheus-operator.md
examples/aks-production/cluster.lokocfg
examples/aks-testing/cluster.lokocfg
examples/aws-production/cluster.lokocfg
examples/aws-testing/cluster.lokocfg
examples/packet-production/cluster.lokocfg
examples/packet-testing/cluster.lokocfg
pkg/components/prometheus-operator/component.go
pkg/components/prometheus-operator/component_test.go
pkg/components/prometheus-operator/template.go
pkg/components/types/types.go

Fixes: https://github.com/kinvolk/lokomotive/issues/456

Add variable `grafana_ingress_host` to expose Grafana

---

docs/configuration-reference/components/httpbin.md

The markdown table is broken due to a missing '|'.

docs/httpbin: Fix table

---

Makefile

Makefile: Previously it was hardcoded to linux. deleting it as go can automatically detect it`. Fixes #526

Deleting machine GOOS from Makefile for  build-slim and  install-slim 

---

pkg/components/dex/component.go

- Dex release: https://github.com/dexidp/dex/releases/tag/v2.24.0.
- Update the image(alpine/git) version of initContainer that downloads
theme to v2.24.3.

dex: Update to v2.24.0

---

pkg/components/prometheus-operator/template.go

This enables the application grafana to know where it is being exposed
over the internet. This makes sure that the invite URLs are not over
default `localhost` but over the user provided external URL.
Fixes #546

Grafana: Provide root_url in grafana.ini conf

---

pkg/terraform/doc.go
pkg/terraform/executor.go
pkg/terraform/signals.go

Fixes #329 
Registers a Signal handler for terraform process and components installation/deletion.
Before running the `lokoctl cluster apply`
```
ps ef | grep terraform | wc -l
0
```
```
module.packet-liger.data.ct_config.controller-install-ignitions[0]: Refreshing state...
module.worker-madrid.data.ct_config.install-ignitions: Refreshing state...
module.worker-madrid.packet_device.nodes[0]: Creating...
module.packet-liger.packet_device.controllers[0]: Creating...
module.worker-madrid.packet_device.nodes[0]: Still creating... [10s elapsed]
module.packet-liger.packet_device.controllers[0]: Still creating... [10s elapsed]
^CInterrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
Stopping operation...
```
After Ctrl + C
```
ps ef | grep …
```

Handle OS interrupts in lokoctl to fix leaking terraform process.

---

docs/concepts/dns.md
docs/configuration-reference/backend/s3.md

For the Route 53 DNS provider and the S3 configuration backend.
I didn't touch the quickstarts yet since they're being reworked.
Fixes https://github.com/kinvolk/lokomotive/issues/373

docs: document Route 53 and S3+DynamoDB permissions

---

test/calico/metadata_access_test.go
test/components/util/util.go

Currently master pipeline fails because of this.

test/calico/metadata_access_test.go: add support for aws_edge platform

---

cli/cmd/component-delete.go
docs/cli/lokoctl_component_delete.md

Add `--confirm` flag to delete component without asking for confirmation

---

docs/configuration-reference/components/prometheus-operator.md

Addresses: #434
This commit adds a note to the user for adding the file to `.gitignore`
to avoid leaking of sensitive data.
We also provide an alternate way of providing alertmanager
configuration to the component, instead of `file()` function we use the
variable and store the content in `lokocfg.vars`

docs: provide alternate way of declaring alertmanager config

---

docs/configuration-reference/platforms/aws.md
examples/aws-production/cluster.lokocfg
examples/aws-testing/cluster.lokocfg
examples/packet-production/cluster.lokocfg
examples/packet-testing/cluster.lokocfg

If Flatcar channels are not explicit, it is difficult for the user to find out how to change them. It also makes it less likely to forget to change it in the worker pool section.
Also fix a typo in the configuration.

examples: make Flatcar channels explicit

---

ci/aws/aws-cluster.lokocfg.envsubst
ci/packet-arm/packet-arm-cluster.lokocfg.envsubst
ci/packet/packet-cluster.lokocfg.envsubst
docs/configuration-reference/platforms/packet.md
pkg/platform/packet/packet.go
pkg/platform/packet/template.go
test/system/clc_snippets_test.go

- Adds Tags field for WorkerPool
- Adds ControllerCLCSnippets for Controller
- Adds CLCSnippets for WorkerPool
The above mentioned fields are part of lokomotive-kubernetes  under
assets/lokomotive-kubernetes but they are not exposed to the user on
Lokomotive.

Packet: Add clc snippets,tags to worker_pool and clc snippets to controller

---

pkg/platform/packet/packet.go

Due to 2 merges into master branch in parallel, building broke. This commit
fixes it.

pkg/platform/packet: fix building

---

pkg/components/prometheus-operator/component.go
pkg/components/prometheus-operator/template.go
test/monitoring/grafana_password_test.go
test/monitoring/monitoring_test.go

Fixes issue where grafana dashboard password is not random when user
does not provide the grafana block.
Fixes https://github.com/kinvolk/lokomotive/issues/506
---
TODOs:

prometheus operator grafana: Generate password random, always

---

docs/quickstarts/packet.md

This PR improves the quickstart guide for Packet. Main improvements:
- Include all necessary information in the text.
- Remove unnecessary information.
- Use a simple config instead of a production-ready one.
- Fix tone and phrasing.
- Remove instructions for things which should be satisfied by requirements.
Addresses part of https://github.com/kinvolk/lokomotive/issues/273.

Make Packet quickstart quick

---

pkg/components/aws-ebs-csi-driver/component.go

In f0f21f383e8e6ddfe43ef5ecd065da7ea66ea0e0 we removed
util.RenderTemplate function and replaced it with template.Render.
However, due to base branch being outdated, this broke buliding master
branch, so this commit fixes it.

pkg/components/aws-ebs-csi-driver: fix building

---

docs/quickstarts/baremetal.md

The clustername was missing double quotes `"` hence add those so that
config is usable after copy pasting.

baremetal quickstart: Add double quotes

---

ci/aws/aws-cluster.lokocfg.envsubst

This reverts commit 1a4dd255efd381d8fa883f573dd3b1c27d75c3d0.
In 20b7b696a61ba6ec706140feeaae6c25dfb3dfae we reverted the naming of
worker pools so we need this again for CI to behave.

Revert "ci/aws: Remove duplicate info in worker pool name"

---

cli/cmd/root.go
cli/cmd/utils.go
cli/cmd/utils_internal_test.go
docs/cli/lokoctl.md
docs/cli/lokoctl_cluster.md
docs/cli/lokoctl_cluster_apply.md
docs/cli/lokoctl_cluster_destroy.md
docs/cli/lokoctl_component.md
docs/cli/lokoctl_component_apply.md
docs/cli/lokoctl_component_delete.md
docs/cli/lokoctl_component_list.md
docs/cli/lokoctl_component_render-manifest.md
docs/cli/lokoctl_health.md
docs/cli/lokoctl_version.md

This PR renames `--kubeconfig` flag to `--kubeconfig-file`  to avoid automatic reading of `KUBECONFIG` environment variable by viper and adds explicit read of `KUBECONFIG` variable **after** cluster configuration in the hierarchy, when selecting `kubeconfig` file to use.
For the time being, there is no tests for this patch, as testing that is not trivial to implement (involves creating lokocfg configuration file in temporary directory, testing private method, and testing viper flags parsing.
Closes #595.

cli/cmd: rename --kubeconfig flag to --kubeconfig-file

---

ci/aks/aks-cluster.lokocfg.envsubst
ci/aws/aws-cluster.lokocfg.envsubst
ci/packet/packet-cluster.lokocfg.envsubst
docs/configuration-reference/components/prometheus-operator.md
pkg/components/prometheus-operator/component.go
pkg/components/prometheus-operator/template.go
test/components/prometheus-operator/prometheus_operator_test.go

This variable allows users to provide arbitrary key values pairs that
will be exposed as environment variables inside the Grafana pod.
Using this functionality user can manipulate `grafana.ini` file. All the
values under `grafana.ini` can be replaced with environment variables in
following format:
`GF_<SectionName>_<KeyName>`.
Where the section name is the text within the brackets(for e.g.
`[auth.google]`). Everything should be upper case, `.` should be
replaced by `_`.
Fixes https://github.com/kinvolk/lokomotive/issues/538

grafana: Add secret_env variable

---

pkg/components/rook-ceph/manifests.go

This adds parameters to the storage class `rook-ceph-block` created by rook-ceph component. This will enable the PVs created by the storage class to be resized on the fly.
---
Once this is merged one can update the `StorageClass` by simply applying the `rook-ceph` component again by running following command:
```bash
lokoctl component apply rook-ceph
```
All the PVs created with older `StorageClass` lack following information:
```yaml
apiVersion: v1
kind: PersistentVolume
...
spec:
csi:
controllerExpandSecretRef:
name: rook-csi-rbd-provisioner
namespace: rook
```
This can be patched, but it has to be done manually:
```bash
export namespace=default
export pvcname=populate-1
kubectl patch pv $(kubectl -n $namespace get pvc $pvcname -o jsonpath='{.spec.volumeName}') --patch …
```

rook-ceph: Allow volume resizing

---

docs/concepts/aws.md

docs/concepts/aws.md: document TLS handshake errors in kube-apiserver

---

examples/aks-production/cluster.lokocfg
examples/aks-testing/cluster.lokocfg
pkg/platform/aks/aks.go
pkg/platform/aks/template.go
pkg/platform/aws/template.go
pkg/platform/baremetal/template.go
pkg/platform/packet/template.go

AKS updates and fixes

---

docs/development/README.md
docs/development/updating-components.md
scripts/find-updates.sh

I used this script to identify the updates that are needed to the components we incorporate into Lokomotive.

Find updates of the components that make Lokomotive

---

cli/cmd/utils.go

cli/cmd/utils.go: fix typo environent -> environment

---

.codespell.ignorewords
.codespell.skip
Makefile

This commit adds 'codespell' target to the Makefile and adds it to 'all'
target, so it is run when all checks are requested, but only if the
binary is present, as some people may not have it installed.
Part of #573

Makefile: add codespell target with configuration

---

ci/packet-arm/packet_arm-cluster.lokocfg.envsubst
ci/packet_arm
test/calico/metadata_access_test.go
test/components/util/util.go

So CI can be configured to use packet_arm instead of packet-arm
gracefully.
This is to make packet-arm consistent with aws_edge. As - cannot be used
as in Go build tags, we changed aws-edge to aws_edge.
Part of #563.

Add packet_arm as alias to packet-arm

---

.codespell.skip

So when we enable spell checking on CI, builds will still be passing.

.codespell.skip: ignore typos in Calico CDRs

---

.goreleaser.yml

Originally the idea with marking releases as pre-releases was that
releases before 1.0.0 should be pre-releases.
However, this doesn't seem to be the intention of the check. It's more
oriented towards alpha or RC releases before a final release is cut.
Marking a release as pre-release also prevents it from appearing on the
main repo page.

goreleaser: stop marking releases as pre-releases

---

pkg/platform/aks/template.go
pkg/platform/aws/template.go
pkg/platform/baremetal/template.go
pkg/platform/packet/template.go

This commit adds 'sensitive = true' to all Terraform outputs, so they
don't show up, when we run 'terraform apply' from the code. This is
to avoid cluttering the user output, as those values are information,
which user don't need to see.
As far as I know, adding 'sensitive = true' is the only way in Terraform
to hide this output, even though the values itself are not really
sensitive.
Closes #625

Don't show release values when running Terraform

---

Makefile

To avoid misbehavior between running lint locally and on CI, make lint
target fail if user has invalid git configuration and suggest how to
resolve that.

Makefile: error on bad git settings when linting 

---

docs/concepts/aws.md
docs/concepts/flatcar-container-linux.md
docs/concepts/packet.md

Related to https://github.com/kinvolk/lokomotive/issues/590

docs: Add CLC Snippet documentation for AWS and Packet

---

docs/configuration-reference/components/rook-ceph.md
pkg/components/rook-ceph/component.go
pkg/components/rook-ceph/manifests.go

Add a variable `enable_toolbox` to install Rook Ceph toolbox pod to
manage and configure Ceph.
Fixes https://github.com/kinvolk/lokomotive/issues/594

rook-ceph: Add toolbox configs

---

cli/cmd/cluster-apply.go
cli/cmd/component-delete.go
cli/cmd/health.go
pkg/components/util/install.go
pkg/k8sutil/client.go
pkg/k8sutil/client_test.go

As a first step towards resolving #608, this PR changes `NewClientset` to create Kubernetes Clientset from `kubeconfig` file **content**, instead of from file **path**. The clients are changes to manually load the file content, which should simplify changing it to also accept the file content as an argument in the upcoming patches.

pkg/k8sutil: change NewClientset to load kubeconfig from file content, not from path

---

docs/development/README.md

docs/development: add section about codespell

---

docs/how-to-guides/monitoring-with-prometheus-operator.md

Fixes: https://github.com/kinvolk/lokomotive/issues/450

docs: How to setup monitoring stack?

---

pkg/platform/aks/aks.go

1.16.9 is not available anymore.

pkg/platform/aks: update Kubernetes version to 1.16.10

---

pkg/components/prometheus-operator/template.go

Add the http scheme to the `externalUrl` field to avoid redirects when deployed.
Fixes: https://github.com/kinvolk/lokomotive/issues/729

prometheus-operator: Fix the redirects

---

docs/how-to-guides/authentication-with-dex-gangway.md

The link is currently broken because it has two ../ instead of just one.

Fix link to the dex component reference

---

CHANGELOG.md
pkg/version/version.go

Release v0.3.0

---

docs/configuration-reference/components/prometheus-operator.md

When installing the prometheus-operator component, the instructions don't mention that the cert-manager component is needed if HTTPS is going to work. The example config assumes there is such a cert as it includes a `certmanager_cluster_issuer = "letsencrypt-production"` line, but doesn't point to the separate component.
This commit adds a link to the component as a requirement. I wasn't sure on the exact wording. Better wording welcome.

Make it obvious that cert-manager is required

---

cli/cmd/cluster-apply.go
cli/cmd/cluster.go
cli/cmd/component-apply.go
cli/cmd/component-delete.go
cli/cmd/health.go
cli/cmd/utils.go
cli/cmd/utils_internal_test.go
pkg/components/util/install.go
pkg/components/util/install_test.go
pkg/k8sutil/doc.go
pkg/k8sutil/getter.go
pkg/k8sutil/getter_test.go
test/components/install_test.go
test/components/util/util.go
vendor/k8s.io/client-go/discovery/cached/memory/memcache.go
vendor/modules.txt

**This PR includes commits from #628, please review this one first and don't leave commit comments for this PR here.**
This PR changes a lot of the code to accept kubeconfig content rather than kubeconfig path, so we will be able to read it from Terraform state/output in the future, which is needed for #608. It also shows, how poorly the code is structured, as such change requite so much code changes. We should make most of this function to execute in the scope/context (so make them have a receiver), which already has access to the kubeconfig content, as the kubeconfig content is almost constant in calls of this functions.
Please review the PR commit by commit, as each of them contains small, logical and independent changes, described a bit in commit message.
Now that reading kubeconfig …

Pass kubeconfig content around rather than file path

---

test/components/prometheus-operator/prometheus_operator_test.go

As global 'go test' timeout is 10 minutes, having 10 minutes here as
well results in triggering the panic caused by global timeout.

test/components/prometheus-operator: reduce test timeout

---

docs/how-to-guides/rook-ceph-storage.md

This document enlists steps that will help user setup storage using Rook Ceph component

docs: Add "How to setup storage using Rook Ceph?"

---

docs/how-to-guides/monitoring-with-prometheus-operator.md

This doc explains users how to add custom monitoring resources like
Grafana dashboards, Prometheus scrape targets using ServiceMonitors,
alerts using PrometheusRules.

docs: How to add custom monitoring resources

---

pkg/components/util/helm.go
pkg/components/util/helm_test.go
pkg/k8sutil/create.go

As part of upstream Helm chart sanitization, we remove all Namespace
objects, as we create them manually before the release is installed,
otherwise Helm will complain. This is the solution from times, where
charts were not updates to not include or conditionally include the
namespace and Helm (v2) was storing all release objects in kube-system
namespace.
This commit changes this behavior to only filter single namespace
object, which is where we will be installing the release. This patch
aims to fix the installation of charts, which spans across multiple
namespaces like for example linkerd.
Right now, many helm charts offers an option to disable namespace
creation already, which we should eventually utilize and disable the
filtering completely, as it is confusing and brings non-obvious …

pkg/components/util: only filter release namespace

---

Makefile

This is the latest version now available.

Makefile: update used golangci-lint version to v1.30.0

---

test/components/util/util.go

Initial CI run should show up which tests are false-negative. Next I'll push a fix for them.

e2e: Fix checking pods in CrashLoopBackoff state

---

test/components/util/util.go

So if `Deployment` or `DaemonSet` fails, we get debug information in CI logs. Note, that this will only help in some cases, perhaps we should also log pod status/events.

test/components/util: print pod logs if waiting for pods fails

---

Makefile

linter: disables gci linter from golangci-lint

---

.codespell.skip
pkg/components/cluster-autoscaler/component.go
pkg/components/cluster-autoscaler/component_internal_test.go

Considering following real-life scenario:
- User X creates cluster A named "foo".
- User X creates cluster B also named "foo" (Packet allows that).
- User Y creates cluster C named "bar".
All clusters are created in the same facility.
Now, if user Y tries to install cluster-autoscaler component, it will
fail, as facility have 2 devices with the same name, despite they don't
even belong to user Y clusters.
This is because we check device uniqueness before checking the cluster
name on the devices, which seems incorrect.
This commit breaks down 'getWorkerUserdata()' function into few smaller
functions to make it more readable and to allow implementing simple
tests for the desired behavior.
Also, previously we were returning userData of last node found and now
we return userData of first …

pkg/components/cluster-autoscaler: fix checking device uniqueness

---

docs/quickstarts/packet.md

Currently it's not possible to deploy the latest lokomotive release on Packet without specifying the machine type. Figuring out the right parameters in the config takes a while. Make this easier by adding them to the example config.

Packet Quickstart: add machine types to the example config

---

pkg/dns/dns.go
pkg/platform/packet/packet.go
pkg/terraform/executor.go
pkg/terraform/executor_test.go

This PR paves the way towards https://github.com/kinvolk/lokomotive/issues/716. By making `terraform.Executor` accept an arbitrary series of "steps" we can now declaratively define the infrastructure pieces a platform is composed of.
Example:
```go
steps := []terraform.ExecutionStep{
{
Description: "create controllers",
Args: []string{
"apply",
"-auto-approve",
fmt.Sprintf("-target=module.packet-%s.packet_device.controllers", c.ClusterName),
},
},
{
Description: "create DNS records",
Args:        []string{"apply", "-auto-approve", "-target=module.dns"},
},
{
Description: "refresh Terraform state",
Args:        []string{"refresh"},
},
{
Description:      "complete infrastructure creation",
Args:             []string{"apply", "-auto-approve"},
// Verify DNS entries were manually created by …
```

Refactor Terraform executor

---

Makefile

Linter should be quiet if there is no issues to report. I suspect this
was mistakenly added in ff08e54e1d562289890a14ebada8ca19e3a0529a while
the migration to config file has been tested.

Makefile: don't use --verbose while running golangci-lint

---

cli/cmd/cluster-apply.go
pkg/components/cert-manager/component.go
pkg/components/cluster-autoscaler/component.go
pkg/components/dex/component.go
pkg/components/external-dns/component.go
pkg/components/flatcar-linux-update-operator/component.go
pkg/components/gangway/component.go
pkg/components/httpbin/component.go
pkg/components/metallb/component.go
pkg/components/metrics-server/component.go
pkg/components/openebs-storage-class/component.go
pkg/components/prometheus-operator/component.go
pkg/components/rook-ceph/component.go
pkg/components/velero/velero.go
pkg/dns/dns.go
pkg/helm/charts.go
pkg/install/install.go
pkg/install/verify.go
pkg/k8sutil/create.go
pkg/platform/aws/aws.go
pkg/platform/baremetal/baremetal.go
pkg/platform/packet/packet.go
pkg/terraform/util.go
test/calico/calico_test.go

This commit partially addresses issue #59, which encourages to use new
error wrapping semantics available since Go 1.13, using %w formating
verb instead of 3rd party 'pkg/errors' package.
This commit changes errors handling code from using errors.Wrap with
fmt.Errorf where error handling should remain as is. For other uses of
errors.Wrap, it adds a comment with TODO how code should be changed to
either avoid or delegate error handling to someone else.

Use fmt.Errorf instead of errors.Wrap where error handling make sense

---

docs/quickstarts/aws.md
docs/quickstarts/baremetal.md
docs/quickstarts/packet.md

PR #835 updated the provider from `v0.5.0` to `v0.6.1` but didn't update the docs. Trying to deploy a cluster with `v0.5.0` results in an error.

docs/quickstarts: Update required ct provider version

---

docs/how-to-guides/upgrade-bootstrap-kubelet.md

Fixes https://github.com/kinvolk/lokomotive/issues/429
---
I have tested it with rook ceph. But not with openebs or with ingress components(metallb, contour).

docs: How to upgrade bootstrap kubelet?

---

go.mod
go.sum
pkg/backend/s3/s3.go
pkg/components/dex/component.go
pkg/components/gangway/component.go
pkg/components/httpbin/component.go
pkg/components/metallb/component.go
pkg/components/openebs-storage-class/component.go
pkg/components/rook-ceph/component.go
pkg/platform/aws/aws.go
pkg/platform/baremetal/baremetal.go
pkg/platform/packet/packet.go

Even though all of them should actually be removed, this commit finishes
the migration to 'fmt.Errorf' for the sake of consistency and
effectively drops the direct dependency on 'github.com/pkg/errors'.
Closes #59

Replace remaining uses of github.com/pkg/errors with fmt

---

cli/cmd/completion.go
cli/cmd/component-apply.go
cli/cmd/component-delete.go
docs/cli/lokoctl_completion.md
docs/cli/lokoctl_completion_bash.md
docs/cli/lokoctl_completion_zsh.md

Add autocomplete for bash and zsh in lokoctl

---

cli/cmd/cluster-apply.go
pkg/platform/aks/aks.go
pkg/platform/platform.go

See commit messages for the details.
Closes #855

Introduce platform.PostApplyHook interface and implement it for AKS cluster

---

pkg/platform/aws/aws.go
pkg/platform/aws/aws_internal_test.go

Add validation check for multiple worker pools, to avoid conflicting
port values in aws_lb_listener. User has to set unique values for
lb_http_port and lb_https_port.
Part of #839

aws: Add check for multiple worker pools

---

docs/configuration-reference/components/rook.md
pkg/components/rook/component.go
pkg/components/rook/manifests.go

This commit adds two new attributes: `csi_plugin_node_selector` and
`csi_plugin_toleration` which will enable the plugin pods to install the
necessary plugins on non-ceph nodes.

rook ceph: Add CSI plugin affinity & toleration attribute

---

Makefile
cli/cmd/cluster-apply.go
cli/cmd/cluster.go
cli/cmd/component-apply.go
cli/cmd/component-delete.go
cli/cmd/health.go
cli/cmd/root.go
cli/cmd/utils.go
cli/cmd/utils_internal_test.go
docs/cli/lokoctl.md
docs/cli/lokoctl_cluster.md
docs/cli/lokoctl_cluster_apply.md
docs/cli/lokoctl_cluster_destroy.md
docs/cli/lokoctl_completion.md
docs/cli/lokoctl_completion_bash.md
docs/cli/lokoctl_completion_zsh.md
docs/cli/lokoctl_component.md
docs/cli/lokoctl_component_apply.md
docs/cli/lokoctl_component_delete.md
docs/cli/lokoctl_component_list.md
docs/cli/lokoctl_component_render-manifest.md
docs/cli/lokoctl_health.md
docs/cli/lokoctl_version.md
go.mod
pkg/platform/aks/template.go
pkg/platform/aws/template.go
pkg/platform/baremetal/template.go
pkg/platform/packet/template.go

**This PR includes commits from #631, please review this one first and don't leave commit comments for this PR here.**
TODO:
Closes #608

cli/cmd: implement kubeconfig fallback to Terraform state

---

ci/aws/aws-cluster.lokocfg.envsubst

It looks like with 2 i3.large instances, istiod sometimes gets stuck in
Pending state due to insufficient CPU.
Closes #887

ci/aws: increase number of worker nodes to 3

---

cli/cmd/cluster.go

Since 474abab61cfc7bf33aeb91ea8682f5f7228d986d, we support also
installing controlplane components in namespaces other than kube-system.
On fresh installation, those namespaces are being created by bootkube.
However, in scenario when user upgrades from the previous release, we
also need to ensure that custom namespace exists, so this commit does
that by instructing Helm to use CreateNamespace feature.

cli/cmd: fix re-installing controlplane components in custom namespaces

---

Makefile

Building the codebase before running the linter adds over 20 seconds to the run time of `make lint`:
```
time make lint
CGO_ENABLED=0 GO111MODULE=on go build \
-mod=vendor \
-ldflags "-X github.com/kinvolk/lokomotive/pkg/version.Version=`git describe --tags --always` -extldflags '-static'" \
-buildmode=exe \
-o lokoctl \
github.com/kinvolk/lokomotive/cmd/lokoctl
go test -run=nonexistent -mod=vendor -tags="aws,packet,aks,e2e,baremetal,disruptivee2e,poste2e" -covermode=atomic -buildmode=exe -v ./... > /dev/null
golangci-lint run --new-from-rev=$(git merge-base $(cat .git/resource/base_sha 2>/dev/null || echo "origin/master") HEAD) ./...
make lint  132.99s user 11.97s system 615% cpu 23.556 total
```
```
time make lint
golangci-lint run --new-from-rev=$(git merge-base $(cat …
```

Makefile: Don't build before linting

---

docs/how-to-guides/upgrade-etcd.md

When upgrading the etcd version of a node, you need to update the local
etcd cluster configuration. The previous sed expression missed appending
an ending double quote to the `ETCD_IMAGE_TAG` environment variable.
This prevented the correct version from being installed, hence not
updating at all.
Closes #920

docs: fix etcd version upgrade sed expression

---

pkg/components/metallb/manifests.go

Add the severity label "critical" to the MetalLB alerts, using the same
approach as the alerts configured by the prometheus-operator.
When any of these alerts are triggered, this could impact any
load balancer/ingress, therefore labeling them as critical.

feat: add severity labels to MetalLB alerts

---

pkg/components/metallb/component.go

This fixes a bug which causes MetalLB speaker tolerations to be applied to controller pods, too.
Tests should be added as part of https://github.com/kinvolk/lokomotive/pull/927.

component/metallb: Fix controller tolerations

---

CHANGELOG.md

Fixes some typo's in the v0.4.0 release notes for the Rook Ceph upgrade
steps

docs: fix rook version update command

---

pkg/components/metallb/component_test.go
pkg/components/metallb/manifests.go

- Remove the tolerations.
- Remove the nodeSelector from yaml and move the golang templated block down.

MetalLB: Fix regressions of tolerations and nodeSelectors

---

pkg/platform/platform.go
pkg/platform/platform_test.go

Also, added test to check the order

Fix controlplane components order

---

pkg/components/rook/component.go
pkg/components/rook/component_test.go

Earlier it was looping through map so output was not consistent.
Closes: #942

Fix output of `convertNodeSelector` in rook

---

cli/cmd/component-apply.go
cli/cmd/component-delete.go
cli/cmd/health.go
pkg/components/aws-ebs-csi-driver/component_test.go
pkg/components/istio-operator/component.go
pkg/components/linkerd/component.go
pkg/components/linkerd/component_test.go
pkg/components/metallb/component_test.go
pkg/components/prometheus-operator/component_test.go
pkg/components/util/helm_test.go
pkg/platform/platform.go
pkg/terraform/executor.go
test/components/aws-ebs-csi-driver/aws-ebs-csi-driver_test.go
test/components/linkerd/linkerd_test.go
test/components/prometheus-operator/prometheus_operator_test.go
test/monitoring/components_alerts_test.go
test/monitoring/grafana_password_test.go
test/system/clc_snippets_test.go
test/system/ssh_keys_test.go

This commit replaces `// nolint` with `//nolint`, to make it consistent
across the project.

Remove space before nolint comment to make it consistent across the project

---

pkg/components/rook/component_conversion_test.go
pkg/components/rook/manifests.go

- Add tests for rook-ceph
Fixes: https://github.com/kinvolk/lokomotive/issues/932

Override memory limits of rook operator to 512Mi

---

Makefile

As running locally 'make update-assets' will include them, but as git do
not include empty directories, after fresh clone it will be removed, so
the assets won't be consistent.
This find will ensure, that if there are empty directories found,
update-assets will fail with clear message to the developer.

Makefile: complain if assets dir has empty directories

---

cli/cmd/cluster-apply.go
cli/cmd/cluster-destroy.go
pkg/terraform/executor.go
test/ingress/packet_test/match_host_test.go
test/monitoring/components_alerts_test.go

fixed error capitalization

---

docs/concepts/admission-webhook.md

Add document for admission webhook

---

pkg/components/metallb/component_test.go
pkg/components/metallb/manifests.go

In order to allow users to control all supported BGP parameters by
specifying labels in worker pool config, we need to specify mappings
for them.
Fixes #987.
To test this change, deploy a cluster using a config similar to the following:
```hcl
cluster "packet" {
asset_dir        = "./assets"
cluster_name     = "my-cluster"
controller_count = 1
controller_type  = "t1.small.x86"
dns {
provider = "route53"
zone     = "example.com"
}
facility    = "ams1"
project_id = "fake"
ssh_pubkeys       = ["ssh-rsa ..."]
management_cidrs  = ["0.0.0.0/0"]
node_private_cidr = "10.1.1.0/25"
worker_pool "pool-1" {
count     = 2
node_type = "t1.small.x86"
labels    = "metallb.lokomotive.io/hold-time=3s,metallb.lokomotive.io/peer-port=1179"
}
}
component "metallb" {
address_pools = {
default = ["147.1.2.3/32"] …
```

components/metallb: Add missing autodiscovery labels

---

ci/aws/aws-cluster.lokocfg.envsubst
test/components/kubernetes/kubelet_disruptive_test.go

The test was disabled because the runc issue rendered the nodes
unusable,now that it is fixed in flatcar stable it makes sense to enable
it.
Fixes #1002

kubelet e2e: Enable the disruptive test

---

assets/charts/control-plane/calico-host-protection/templates/host-protection.yaml
assets/charts/control-plane/calico/templates/config.yaml
assets/charts/control-plane/calico/templates/felixconfig.yaml
assets/charts/control-plane/calico/values.yaml
assets/terraform-modules/aws/flatcar-linux/kubernetes/bootkube.tf
assets/terraform-modules/aws/flatcar-linux/kubernetes/variables.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/bootkube.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/variables.tf
assets/terraform-modules/bootkube/conditional.tf
assets/terraform-modules/bootkube/resources/charts/calico.yaml
assets/terraform-modules/bootkube/variables.tf
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/bootkube.tf
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/variables.tf
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/bootkube.tf
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/variables.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/bootkube.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/variables.tf
docs/configuration-reference/platforms/aws.md
docs/configuration-reference/platforms/baremetal.md
docs/configuration-reference/platforms/packet.md
pkg/platform/aws/aws.go
pkg/platform/aws/template.go
pkg/platform/baremetal/baremetal.go
pkg/platform/baremetal/template.go
pkg/platform/packet/packet.go
pkg/platform/packet/packet_test.go
pkg/platform/packet/template.go
pkg/platform/platform.go

Calico v3.15+ support wireguard and if enabled it encrypts in-cluster
pod traffic across nodes.
- delete `default FelixConfiguration` while upgrading from 0.4.1
- `network_mtu` changed from CNI network MTU to Physical network MTU.
- `bpfLogLevel` will be briefly set from `Info` to `Off`.
- Following ports will be opened on all hosts for the upgrade time between `calico` chart upgrade and `calico-host-protection` chart:
```
- 22/tcp
- 68/udp
- 179/tcp
- 2379/tcp
- 2380/tcp
- 5473/tcp
- 6443/tcp
- 6666/tcp
- 6667/tcp
```

Add encryption to in-cluster pod traffic

---

assets/terraform-modules/bootkube/assets.tf
assets/terraform-modules/bootkube/outputs.tf

Currently, if one has TLS bootstrap enabled and remove it's assets
directory, assuming that they use remote Terraform backend, Terraform
won't be able to evalue this output, as after refreshing,
local_file.bootstrap-secrets will be gone, as the file has been removed.
This commit moves content rendering to local variable, so module output
does not depend on local file.
Closes #1016

bootkube: feed output using local rather than local_file content

---

docs/how-to-guides/rook-ceph-storage.md

The doc tells the user to update the `rook-ceph` component config and then re-apply the `rook` component, which doesn't make sense.

docs/rook-ceph-storage: Use correct apply command

---

assets/charts/components/dex/templates/deployment.yaml
pkg/components/dex/component_test.go

closes: #1039
Co-authored-by: Mateusz Gozdek <mateusz@kinvolk.io>

Fix dex pod reload on config change

---

docs/KEYS.md

I lost access to the previous private key
(0xBECE2BD4B68D2071255A7A4E3689AD7F72EBB080) so I've added a
iago@kinvolk.io identity to my personal key
(0xB7DDBE7001408D7D7FD079D27E26368261BAD4F7) and I'll be using that key
from now on.
Additionally, I've added the new key to keys.openpgp.org
(https://keys.openpgp.org/search?q=iago%40kinvolk.io) which verifies the
email address associated with the key.

docs/KEYS: switch to personal GPG key

---

cli/cmd/cluster-apply.go
cli/cmd/cluster-destroy.go
cli/cmd/cluster.go
cli/cmd/component-apply.go
cli/cmd/component-delete.go
cli/cmd/utils.go

cli/cmd: cleanups part 1

---

assets/charts/control-plane/kubelet/templates/kubelet-ds.yaml
assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/worker.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
docs/how-to-guides/upgrade-etcd.md

This commit removes rkt and uses docker to start services.
etcd(for controllers only):
- Move the env var to a separate env var file.
- Add etcd service file.
- Change the name of service from etcd-member to etcd.
Bootkube(for controllers only):
- Use `docker run` instead of rkt.
Kubelet(for controllers and workers):
- Remove some of the folder creation in `ExecStartPre`, these are
automatically created by docker, when mounted using `-v` flag.
delete-node(for workers):
- Use `docker run` instead of rkt.
Fixes #720
Fixes #917 
- Change from `etcd-member.service` to `etcd.service`. Old mechanism of running etcd(using etcd-wrapper) entailed we use the Flatcar shipped `etcd-member.service`.
- New etcd env vars file: `/etc/kubernetes/etcd.env` on controller hosts.
- Remove all dependency on …

aws,packet,baremetal: Remove rkt

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/controllers.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/profiles.tf
assets/terraform-modules/bootkube/assets.tf
assets/terraform-modules/bootkube/outputs.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/controllers.tf

template_file is deprecated
closes: #196

remove usage of template_file

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/variables.tf
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/workers.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/variables.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/workers.tf
ci/aws/aws-cluster.lokocfg.envsubst
ci/packet/packet-cluster.lokocfg.envsubst
docs/configuration-reference/platforms/aws.md
docs/configuration-reference/platforms/packet.md
pkg/platform/aws/aws.go
pkg/platform/aws/template.go
pkg/platform/packet/packet.go
pkg/platform/packet/template.go

Commits for more information.
closes: #489 #833
- labels and nodes format changed from `string` to `map(string)` for aws and packet platform.
```
labels = "testing=true"
taints = "nodeType=storage:NoSchedule"
labels = {
"testing" = "true"
}
taints = {
"nodeType" = "storage:NoSchedule"
}
```

labels taints format change

---

test/calico/metadata_access_test.go
test/components/aws-ebs-csi-driver/aws-ebs-csi-driver_test.go
test/components/cert-manager/cert-manager_test.go
test/components/cluster-autoscaler/cluster-autoscaler_test.go
test/components/contour/contour_test.go
test/components/coredns/coredns_test.go
test/components/dex/dex_test.go
test/components/external-dns/external-dns_test.go
test/components/flatcar-linux-update-operator/fluo_test.go
test/components/gangway/gangway_test.go
test/components/httpbin/httpbin_test.go
test/components/istio/istio_test.go
test/components/kubernetes/controller-manager_test.go
test/components/kubernetes/kubelet_disruptive_test.go
test/components/kubernetes/kubelet_test.go
test/components/linkerd/linkerd_test.go
test/components/metallb/metallb_test.go
test/components/metrics-server/metrics_server_test.go
test/components/openebs-operator/openebs_operator_test.go
test/components/patch_serviceaccount_test.go
test/components/prometheus-operator/prometheus_operator_test.go
test/components/rook/rook_test.go
test/components/util/util.go
test/ingress/aws/aws_test.go
test/ingress/packet_test/match_host_test.go
test/monitoring/components_alerts_test.go
test/monitoring/components_metrics_test.go
test/monitoring/scrape_targets_test.go

timeout and retryInterval were the same for most of the components and was
duplicated.
closes: #502

test/*: de-duplicate value timeout and retryInterval

---

assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl

In some Packet facilities the BGP peer address isn't the same as the gateway address allocated for a host. Rather, it is a loopback address that's reachable via the gateway.
The Packet metadata service now exposes BGP info to hosts, so we can query the metadata service for the BGP peer address.
The source address is explicitly specified since when the peer address is a loopback address, the source IP addresses which ends up getting selected by the kernel is the node's *public* address which doesn't work. In cases where the peer address is the gateway address there is no harm in explicitly specifying the source.
Fixes #1009.

packet: Read BGP peer address from metadata service

---

docs/development/coding-style-guide.md

This PR adds an initial code style guide for Lokomotive. The guide currently focuses mainly on Go code, however we could add guidelines for other types of code (e.g. HCL, Markdown).
I find it useful to maintain such a guide as I find myself commenting the same things over and over again in PRs and would love to have a document I could link to. I think that following a common and agreed-upon guide could make code reviews more efficient.
The document should be agreed upon by the team and is expected to evolve over time. The current state is by no means a comprehensive list of guidelines. Rather, it currently contains a small set of initial guidelines which I believe already have consensus in the team so we might as well formalize them.

Add a coding style guide

---

pkg/assets/assets.go
pkg/assets/assets_generate.go
pkg/assets/embedded.go
pkg/assets/fs.go
pkg/assets/walkers.go
pkg/helm/charts.go

~**Includes commits from #935**~
This PR finishes cleaning up API of `pkg/assets` package, so end result is, that only exported function we have is `Extract()`.
See commit messages for more details.
Closes #796

pkg/assets: cleanup exported API

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/versions.tf
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/versions.tf
assets/terraform-modules/azure/flatcar-linux/kubernetes/versions.tf
assets/terraform-modules/azure/flatcar-linux/kubernetes/workers/versions.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/versions.tf
assets/terraform-modules/bootkube/versions.tf
assets/terraform-modules/dns/cloudflare/versions.tf
assets/terraform-modules/dns/route53/versions.tf
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/versions.tf
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/workers/versions.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/versions.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/versions.tf
ci/set-terraform-version
pkg/platform/aks/template.go
pkg/platform/aws/template.go
pkg/platform/baremetal/template.go
pkg/platform/packet/template.go
pkg/terraform/executor.go
pkg/terraform/executor_test.go

~NOTE: Includes commits from #860.~
~NOTE: Includes changes from #1027~
Closes #788

Upgrade to Terraform 0.13

---

docs/configuration-reference/components/metallb.md

This PR clarifies the proper usage of the `address_pools` knob of the `metallb` component.

docs/metallb: Clarify address_pools knob

---

assets/charts/components/headlamp/.helmignore
assets/charts/components/headlamp/Chart.yaml
assets/charts/components/headlamp/templates/_helpers.tpl
assets/charts/components/headlamp/templates/deployment.yaml
assets/charts/components/headlamp/templates/ingress.yaml
assets/charts/components/headlamp/templates/service.yaml
assets/charts/components/headlamp/values.yaml
ci/aks/aks-cluster.lokocfg.envsubst
ci/aws/aws-cluster.lokocfg.envsubst
ci/packet/packet-cluster.lokocfg.envsubst
cli/cmd/component.go
docs/concepts/components.md
docs/configuration-reference/components/headlamp.md
go.mod
pkg/components/headlamp/component.go
pkg/components/headlamp/component_test.go
pkg/components/headlamp/doc.go
pkg/components/headlamp/template.go
test/components/headlamp/headlamp_test.go
test/ingress/aws/aws_test.go
test/ingress/headlamp/ingress_test.go
test/ingress/ingress.go

Fixes https://github.com/kinvolk/lokomotive/issues/988

pkg/components: add Headlamp component 

---

docs/configuration-reference/components/velero.md
docs/how-to-guides/backup-rook-ceph-volumes.md
pkg/components/velero/restic/restic.go
pkg/components/velero/restic/template.go

Add how to guide on backing up and restoring rook-ceph volumes with Velero

---

assets/charts/components/istio-operator/Chart.yaml
assets/charts/components/istio-operator/crds/crd-operator.yaml
assets/charts/components/istio-operator/templates/clusterrole.yaml
assets/charts/components/istio-operator/templates/clusterrole_binding.yaml
assets/charts/components/istio-operator/templates/crds.yaml
assets/charts/components/istio-operator/templates/deployment.yaml
assets/charts/components/istio-operator/templates/istio-namespace.yaml
assets/charts/components/istio-operator/templates/istio-operator-cr.yaml
assets/charts/components/istio-operator/templates/namespace.yaml
assets/charts/components/istio-operator/templates/service.yaml
assets/charts/components/istio-operator/templates/service_account.yaml
assets/charts/components/istio-operator/values.yaml
pkg/components/istio-operator/component.go
pkg/components/istio-operator/component_test.go

Release Notes: https://github.com/istio/istio/releases/tag/1.7.3

istio-operator: Update to 1.7.3

---

cli/cmd/cluster-apply.go
cli/cmd/cluster-destroy.go
cli/cmd/cluster.go
cli/cmd/component-apply.go
cli/cmd/component-delete.go
cli/cmd/utils.go

~**Includes commits from #1013**~
Part of #603.

cli/cmd: cleanups part 2

---

Makefile

Makefile: use latest Go when building in Docker

---

assets/charts/components/gangway/templates/deployment.yaml
assets/charts/components/gangway/templates/serviceaccount.yaml
test/components/gangway/gangway_test.go

Gangway relies on a service account (any service account) to be mounted
on the pod file system to figure out the cluster CA.
We've disabled automounting of the default service account with the
our admission wehbook and this was breaking Gangway.
This creates a dummy service account so the Gangway pod has access to
the cluster CA file.
Fixes #1103 
TODO:

gangway: add a serviceaccount

---

cli/cmd/component-delete.go
pkg/components/util/install.go
test/components/component_delete_multiple_release_test.go

User should know that before deleting a component that other helm
release  exists in a namespace.
closes: #1077

Add check for multiple release in Namespace

---

cli/cmd/cluster-apply.go
cli/cmd/cluster-destroy.go
cli/cmd/cluster.go
cli/cmd/component-apply.go
cli/cmd/component-delete.go
cli/cmd/component-render-manifest.go
cli/cmd/health.go
cli/cmd/root.go
cli/cmd/utils.go
cli/cmd/utils_internal_test.go

~**Includes commits from #1015**~
Part of #603.

cli/cmd: cleanups part 3

---

assets/charts/components/inspektor-gadget/.helmignore
assets/charts/components/inspektor-gadget/Chart.yaml
assets/charts/components/inspektor-gadget/templates/_helpers.tpl
assets/charts/components/inspektor-gadget/templates/daemonset.yaml
assets/charts/components/inspektor-gadget/templates/psp.yaml
assets/charts/components/inspektor-gadget/templates/rbac.yaml
assets/charts/components/inspektor-gadget/templates/serviceaccount.yaml
assets/charts/components/inspektor-gadget/values.yaml
ci/aks/aks-cluster.lokocfg.envsubst
ci/aws/aws-cluster.lokocfg.envsubst
ci/baremetal/baremetal-cluster.lokocfg.envsubst
ci/packet/packet-cluster.lokocfg.envsubst
cli/cmd/component.go
docs/concepts/components.md
docs/configuration-reference/components/inspektor-gadget.md
pkg/components/inspektor-gadget/component.go
pkg/components/inspektor-gadget/component_test.go
pkg/components/inspektor-gadget/doc.go
pkg/components/inspektor-gadget/template.go
test/components/inspektor-gadget/inspektorgadget_test.go

pkg/components: add Inspektor Gadget component

---

test/components/linkerd/linkerd_test.go

linkerd changed the script, due to which it was failing to install
linkerd on fedora. Changed base image to nginx and script accordingly.

test/linkerd: Fix TestLinkerdDeployment

---

CHANGELOG.md
pkg/version/version.go

Release v0.5.0

---

scripts/bump-release.sh

grep -P option is not available on osx. To be merged only after 0.5.0 release

fix bump release for osx

---

assets/charts/components/metrics-server/Chart.yaml
assets/charts/components/metrics-server/README.md
assets/charts/components/metrics-server/templates/role-binding.yaml
assets/charts/components/metrics-server/templates/tests/test-version.yaml
assets/charts/components/metrics-server/values.yaml

metrics-server: update metrics server to 2.11.2

---

docs/CONTRIBUTING.md

The git link in the contribution repository has moved.

docs/CONTRIBUTION.md: Update Contribution repo's git link

---

assets/charts/components/velero/Chart.yaml
assets/charts/components/velero/README.md
assets/charts/components/velero/ci/test-values.yaml
assets/charts/components/velero/crds/backups.yaml
assets/charts/components/velero/crds/backupstoragelocations.yaml
assets/charts/components/velero/crds/deletebackuprequests.yaml
assets/charts/components/velero/crds/downloadrequests.yaml
assets/charts/components/velero/crds/podvolumebackups.yaml
assets/charts/components/velero/crds/podvolumerestores.yaml
assets/charts/components/velero/crds/resticrepositories.yaml
assets/charts/components/velero/crds/restores.yaml
assets/charts/components/velero/crds/schedules.yaml
assets/charts/components/velero/crds/serverstatusrequests.yaml
assets/charts/components/velero/crds/volumesnapshotlocations.yaml
assets/charts/components/velero/templates/cleanup-crd.yaml
assets/charts/components/velero/templates/deployment.yaml
assets/charts/components/velero/templates/restic-daemonset.yaml
assets/charts/components/velero/templates/schedule.yaml
assets/charts/components/velero/templates/serviceaccount-server.yaml
assets/charts/components/velero/values.yaml
pkg/components/velero/openebs/template.go

Release notes: Since this PR also updates the CRD, they need to be manually updated first.
Step before installing the new component:
```
kubectl apply -f https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero/crds
```

Update velero to 1.5.2

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/azure/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl

So smooth out pivoting from bootstrap kube-apiserver to self-hosted one.

Update to bootkube with --wait Helm option

---

docs/configuration-reference/components/velero.md
pkg/components/velero/component.go
pkg/components/velero/component_test.go
pkg/components/velero/openebs/openebs.go
pkg/components/velero/restic/restic.go

Brings back the addition of `provider` field in the component configuration.
This is done so to be able to provide default configurations for the plugins.
Also it removes the default BackupStorageLocation config in restic
plugin.
Name is optional and its default value is `default` in Helm chart.
Provider is required and making it a default of `aws` doesn't make sense
as the user has to provide  value to it anyway.
Region is also specifc to the provider used. If not `aws` then there is
no need to input that value.
Release notes: 
Add `provider` field in the component configuration.
example:
```
component `velero` {
.
.
provider = "openebs"
openebs {
.
.
}
}
```

velero: Add provider field and remove default configuration in restic plugin

---

test/ingress/packet_test/match_host_test.go

As Ingress object will be created first, then Ingress controller will set
it's status, there might be a window where we can receive Ingress object
without all values set which we require.
Instead of failing the test, we should simply retry in this case, as
status should be eventually set.
Also pass testing.T to checkIngressHost() so we can use t.Log there.
Closes #1157

test/ingress/packet_test: retry when ingress has no status set yet

---

assets/charts/components/aws-ebs-csi-driver/Chart.yaml
assets/charts/components/aws-ebs-csi-driver/templates/controller.yaml
assets/charts/components/aws-ebs-csi-driver/templates/node.yaml
assets/charts/components/aws-ebs-csi-driver/templates/storageclass.yaml
assets/charts/components/aws-ebs-csi-driver/values.yaml

aws-ebs-csi-driver: update to v0.7.0

---

pkg/components/cluster-autoscaler/component.go
pkg/components/cluster-autoscaler/component_internal_test.go
test/components/flatcar-linux-update-operator/fluo_reboot_test.go
test/components/flatcar-linux-update-operator/fluo_test.go

**Includes commits from #1167, as otherwise `Packet` pipeline would fail**
See commit messages for details.

test/components/flatcar-linux-update-operator: fix flaky idle test

---

pkg/components/cluster-autoscaler/component.go
pkg/components/cluster-autoscaler/component_internal_test.go

Packet API seems to have a bug, that when you use Project API key
for querying devices, it returns duplicated entries. However IDs
of the devices should be the same, so it should be safe to relax
the check on those, as if there would actually be 2 different devices
with the same name, they should have different IDs.

pkg/components/cluster-autoscaler: fix duplicate device error

---

ci/packet_fluo/packet_fluo-cluster.lokocfg.envsubst
test/components/prometheus-operator/prometheus_operator_test.go

It should've been added in #1084.
Closes #397

Enable e2e tests for Prometheus Operator on Packet FLUO pipeline

---

assets/charts/components/openebs-operator/Chart.yaml
assets/charts/components/openebs-operator/README.md
assets/charts/components/openebs-operator/templates/daemonset-ndm.yaml
assets/charts/components/openebs-operator/templates/deployment-local-provisioner.yaml
assets/charts/components/openebs-operator/templates/deployment-maya-provisioner.yaml
assets/charts/components/openebs-operator/templates/deployment-maya-snapshot-operator.yaml
assets/charts/components/openebs-operator/values.yaml

Updates OpenEBS from `1.12.0` to `v2.2.0.

Update openEBS to v2.2.0.

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/ssh.tf

In previous attempt in e852117992a4a5ae13104a57ebb07dac71f9ed0f, I
missed the fact that Terraform remote-exec only prints stderr to the
user and stdout is ignored. This means, if we redirect journalctl output
to stderr, then it should be printed which will improve debugging
experience.
Refs #440

Print bootkube journal if it fails

---

assets/charts/components/contour/templates/01-contour-config.yaml
assets/charts/components/contour/templates/02-job-certgen.yaml
assets/charts/components/contour/templates/03-contour.yaml
assets/charts/components/contour/templates/03-envoy.yaml
assets/charts/components/contour/values.yaml

contour: update to v.1.10.0

---

pkg/components/openebs-operator/component.go

This commit addresses #1171
OpenEBS by default ships the failurePolicy as 'Fail', however this
causes sometimes to unexpectedly hit a known bug in OpenEBS
https://github.com/openebs/openebs/issues/3046.
One of the workarounds suggested is to change the failurePolicy to
`Ignore`.

fix: openebs-operator webhook issue

---

ci/packet_fluo/packet_fluo-cluster.lokocfg.envsubst
test/platform/packet/packet_test.go

This commit adds e2e test, which verifies, that if worker pool has BGP
disabled on Packet, it actually remains disabled.
This test addresses
https://github.com/kinvolk/lokomotive/issues/548#issuecomment-694826634
to ensure, that we do not introduce a regression while adding CCM
support for Packet, as currentl CCM enables BGP on all workers in the
project, so it is expected that this test will fail with CCM enabled,
unless CCM is modified to only enable BGP on selected nodes.
Refs #548.

Add tests for disabling BGP on Packet

---

assets/charts/control-plane/calico-host-protection/templates/host-endpoint-controller.yaml

As calico-host-protection is now being installed using bootkube, it
requires bootkube to wait for worker nodes to join the cluster to finish
running, which extends running time of bootkube unnecesserily.
I believe all workloads installed using bootkube should be schedulable
on a controller nodes, so make it more robust
Closes #1179

calico-host-protection: allow running controller on controller nodes

---

assets/terraform-modules/packet/flatcar-linux/kubernetes/calico-host-protection.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/ssh.tf

Currently, bootkube installs all charts in parallel, which causes
calico-host-protection chart installation to fail ocasionally, as it
gets installed before Calico chart itself.
This commit adds a workaround for this, by making an extra copy of
Calico CRDs into bootkube manifests directory, as those will be applied
before Helm charts. This ensures, that the CRDs are created before
calico-host-protection is installed, however it is rather hacky and
should not be considered as final solution for the issue, but a
temporary workaround to ensure cluster bootstrapping remains reliable.
More details in issue #1175.
Closes #1175

packet: ensure Calico CDRs gets created before use

---

docs/how-to-guides/upgrade-openebs.md

OpenEBS upgrade guide from 1.12.0 to 2.2.0
Closes #905 
This covers only the upgrade of OpenEBS control plane and data plane components. Migration from non-CSI provisioning to CSI provisioning is not covered and will be added later to this guide based on the following reasons:
* Migration to CSI based provisioning is optional.
* Migration involes a step of installing new set of CRDs and other Kubernetes
manifests, which are not yet part of the OpenEBS helm chart,thus giving rise
to potential issues in future upgrades when the the new // resources are part
of the helm chart.
* Post migration to CSI based provisioning we need to make changes to
`openebs-storage-class` component as the component wouldn't function in latest
version of OpenEBS and ensure that new set of templates don't break …

docs: OpenEBS upgrade guide.

---

assets/charts/control-plane/kube-apiserver/Chart.yaml
assets/charts/control-plane/kube-apiserver/values.yaml
assets/charts/control-plane/kubelet/Chart.yaml
assets/charts/control-plane/kubelet/values.yaml
assets/charts/control-plane/kubernetes/Chart.yaml
assets/charts/control-plane/kubernetes/values.yaml
assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/azure/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/azure/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/worker.yaml.tmpl
assets/terraform-modules/bootkube/variables.tf
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
pkg/platform/aks/aks.go

Update to Kubernetes v1.19.4 and AKS to v1.18.10

---

assets/charts/components/contour/templates/02-job-certgen.yaml

They are already applied for both contour and envoy, so they should also
be applied for job.
Closes #926

contour: apply node affinity and tolerations also to certgen job

---

assets/charts/control-plane/bootstrap-secrets/templates/bootstrap-secret.yaml

They should always be strings. If Terraform generates them to be
numbers-only, Helm will fail installing it.

bootstrap-secrets: always quote values

---

assets/terraform-modules/bootkube/assets.tf
assets/terraform-modules/bootkube/variables.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/bootkube.tf

See commit message for more information
closes: #374 

coredns use version tag

---

.github/workflows/ci.yaml
Makefile

To make build step fail if tests code cannot be compiled and to make clear error before linter runs if code does not compile.

Compile all tests code as part of build process and before linter runs

---

assets/charts/control-plane/calico/values.yaml
assets/charts/control-plane/kubernetes/values.yaml
assets/charts/control-plane/pod-checkpointer/values.yaml
assets/terraform-modules/bootkube/variables.tf

Pull controlplane images from Quay to avoid hitting Docker Hub pulling limits

---

test/system/ssh_keys_test.go

No ubuntu image exists on quay, so changed it to kinvolk nginx repo.
This is to avoid docker pull limit errors.
See build https://yard.lokomotive-k8s.net/builds/43831 for more information

ssh_keys_test image fix

---

pkg/platform/tinkerbell/tinkerbell.go
pkg/platform/tinkerbell/tinkerbell_test.go

45c0f6f13da0658151f94669cd79125ea5be0730,
2ebfb4475b899fb053458adcc558bda542ef5ccc and
f563d565856a8056bf4b2c8b1d14c4d1fd569f96 have been recently merged, in
parallel to adding Tinkerbell platform. Those commits changed how we
unpack controlplane charts and due to no obvious merge conflict,
Tinkerbell code stayed out of date and broke building.
This commit updates Tinkerbell platform to behave the same way as other
platforms.

pkg/platform/tinkerbell: update the way we unpack controlplane charts

---

docs/how-to-guides/upgrade-rook-ceph.md

Add a guide to explain how to upgrade rook-ceph component.
Fixes: https://github.com/kinvolk/lokomotive/issues/906

docs: Rook Ceph Upgrade

---

assets/charts/control-plane/kubelet/templates/kubelet-ds.yaml
assets/charts/control-plane/kubelet/values.yaml
assets/charts/control-plane/packet-ccm/.helmignore
assets/charts/control-plane/packet-ccm/Chart.yaml
assets/charts/control-plane/packet-ccm/templates/deployment.yaml
assets/charts/control-plane/packet-ccm/templates/secrets.yaml
assets/charts/control-plane/packet-ccm/values.yaml
assets/terraform-modules/bootkube/assets.tf
assets/terraform-modules/bootkube/resources/charts/kubelet.yaml
assets/terraform-modules/packet/flatcar-linux/kubernetes/bootkube.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/packet-ccm.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/packet-ccm.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/variables.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/workers.tf
ci/packet_fluo/packet_fluo-cluster.lokocfg.envsubst
pkg/components/metallb/component_test.go
pkg/components/metallb/manifests.go
pkg/platform/packet/packet.go
pkg/platform/packet/template.go
test/components/packet_ccm_test.go
test/platform/packet/packet_test.go

See commits for more information
Closes #548
Closes #1126

Add Packet CCM to Packet platform

---

docs/how-to-guides/upgrade-bootstrap-kubelet.md

Update the instructions for upgrading kubelet doc. This introduces an image replacement command. The clusters created with hyperkube image will fail to implement these instructions if they use hyperkube image of 1.19.x.

kubelet upgrade doc

---

assets/charts/components/web-ui/Chart.yaml
assets/charts/components/web-ui/values.yaml
pkg/components/web-ui/component_test.go
pkg/components/web-ui/template.go

This PR update Web UI to v0.1.3.
Let's use the chart to express version changes since the Headlamp and
Lokomotive Web UI versions are locked to each other. This way we avoid
having to modify the version in the template too.

components/web-ui: bump to v0.1.3

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/controller/templates/bootkube.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl

This commit removes the unnecessary code which pre pulled images when kubelet was run by rkt. Now it is not needed to do anymore.

Don't prepull the kubelet images

---

assets/terraform-modules/platforms/tinkerbell/controllers/ssh.tf

Instead of piping everything to stderr we should use --no-pager to get
logs printed correctly.

tinkerbell: fix printing bootkube logs on error

---

assets/charts/components/contour/templates/service-monitor.yaml
assets/charts/components/contour/values.yaml
docs/configuration-reference/components/contour.md
pkg/components/contour/component.go
pkg/components/contour/component_test.go
pkg/components/contour/manifest.go

This commit adds a parameter to contour's component config, using which now users can choose what (prometheus) scrape interval they want for envoy.
Deploy contour using following config:
```tf
component "contour" {
enable_monitoring = true
envoy {
metrics_scrape_interval = "30s"
}
}
```
And you can watch the field `interval` vary according to the value of `metrics_scrape_interval`. If the field `metrics_scrape_interval` is not provided then the `interval` field is also left out.
```bash
kubectl -n projectcontour get servicemonitor envoy -o yaml | grep interval
```
Fixes: #1194

contour: parameterise envoy scraping interval

---

pkg/components/contour/component_test.go

#1229 seems to have broken the tests of the `contour` component. This fixes them.

components/contour: Fix tests

---

assets/charts/control-plane/kubernetes/templates/kube-scheduler-role-binding.yaml

added a rolebinding for role `extension-apiserver-authentication-reader` for kube-scheduler
closes: #1096

kube-scheduler: fix access to cluster certificates ConfigMap

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/ami.tf
assets/terraform-modules/aws/flatcar-linux/kubernetes/controllers.tf
assets/terraform-modules/aws/flatcar-linux/kubernetes/variables.tf
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/ami.tf
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/variables.tf
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/workers.tf
assets/terraform-modules/azure/flatcar-linux/kubernetes/versions.tf
assets/terraform-modules/azure/flatcar-linux/kubernetes/workers/versions.tf
pkg/platform/aws/aws.go
pkg/platform/aws/template.go

Remove Deprecated CoreOS from AWS terraform

---

assets/charts/control-plane/kubelet/container-image/Dockerfile
assets/charts/control-plane/kubelet/container-image/README.md
assets/charts/control-plane/kubelet/container-image/iscsiadm
assets/charts/control-plane/kubelet/templates/kubelet-ds.yaml
assets/charts/control-plane/kubelet/values.yaml
assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/azure/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/azure/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/worker.yaml.tmpl
assets/terraform-modules/bootkube/variables.tf
assets/terraform-modules/controller/variables.tf
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/node/variables.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/worker/main.tf
assets/terraform-modules/worker/variables.tf
docs/how-to-guides/upgrade-bootstrap-kubelet.md

- Create iscsi initiator name on workers
- Enable `iscsid` service on baremetal.
- With new Flatcar `2605.9.0` the `/etc/iscsi` directory is shipped and the initiator name file (`/etc/iscsi/initiatorname.iscsi`) has incomplete config which causes the `iscsid` process to start with warning that the initiator name is improper. This PR makes sure that the initiator name is proper. More explanation: https://github.com/kinvolk/lokomotive/issues/1257#issuecomment-743050474.
- This PR adds a `ExecPreStart` which creates `iscsid` initiator name file.
- Remove deprecated `enable: true` for the existing `iscsid` service configuration.
- We can use the script `iscsi-gen-initiatorname` but it creates the initiator name with FQDN `suse.de` in it, so this script creates the initiator name with FQDN …

Fix iscsi volume mount issue

---

Makefile
ci/scripts/deploy-cluster.sh

This commit adds the script which sets up the test cluster to run on CI.
This script can be run using a make receipe `deploy-ci-cluster`.

CI: Add setup test cluster script

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/aws/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/azure/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/controller/variables.tf
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/platforms/tinkerbell/controllers/ssh.tf

To include https://github.com/kinvolk/bootkube/pull/19
~Draft to make sure it works as expected before I merge PR above and tag it. Doing some local tests too.~
Okay, it works as expected:
```console
module.aws-l8e-mat.null_resource.bootkube-start: Creating...
module.aws-l8e-mat.null_resource.bootkube-start: Provisioning with 'file'...
module.aws-l8e-mat.null_resource.bootkube-start: Still creating... [10s elapsed]
module.aws-l8e-mat.null_resource.bootkube-start: Provisioning with 'remote-exec'...
module.aws-l8e-mat.null_resource.bootkube-start (remote-exec): Connecting to remote host via SSH...
module.aws-l8e-mat.null_resource.bootkube-start (remote-exec):   Host: 54.93.82.231
module.aws-l8e-mat.null_resource.bootkube-start …
```

Update bootkube to include timeout fixes

---

assets/charts/components/dex/Chart.yaml
assets/charts/components/dex/templates/deployment.yaml

Switched registry to ghcr.io for dex deployment
closes: #1268

dex: Update to v2.27.0

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/worker.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
docs/concepts/logging.md
test/system/docker_live_restore_test.go

Earlier if the docker daemon was restarted the containers would be restarted as well. This PR enables live restore where containers are not restarted.
This PR also adds log options where if the container log size is more than 100MB then docker daemon creates new log file and only three such log files are kept around.
Fixes #1220
Fixes #1221 
- Install a cluster on Packet or AWS or Baremetal with this change. To test the change also install these components to perform tests `openebs-operator`, `openebs-storage-class`, `prometheus-operator`, `contour`, `metallb`, `httpbin`, `external-dns`.
- ssh into any machine of the cluster and look for file `/etc/docker/daemon.json`.
- Start a pod in the cluster to stress the application from:
```bash
kubectl run -it --rm debug-network-$RANDOM …
```

Add docker log options and enable live restore

---

ci/scripts/deploy-cluster.sh

This commit adds a check to disable ssh key creation when the platform
is tinkerbell. This is a regressions introduced since moving from ci
based script that created clusters vs the script in lokomotive repo that
creates a cluster.
Without this code the pipeline stays stuck in interactive y/n question to overwrite the key.

deploy-cluster: Don't create ssh key for tinkerbell

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/variables.tf
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/workers.tf
pkg/platform/aws/template.go

Fixes: #1219
Whe trying to dynamically provision EBS volumes using the AWS EBS CSI
driver, we run into an error:
```
E1217 08:08:41.495598       1 driver.go:111] GRPC error: rpc error: code
= Internal desc = NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the
environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
```
There reason being that worker nodes are not given this permissions as
mentioned in the github repo of [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver#set-up-driver-permission).
This commit adds such permissions to the worker nodes.

aws_ebs_csi_driver: fix permission issue

---

assets/charts/components/aws-ebs-csi-driver/crds/snapshotter.yaml
docs/configuration-reference/components/aws-ebs-csi-driver.md
pkg/components/aws-ebs-csi-driver/component.go

Closes: #1278 
Enhances the aws-ebs-csi-driver with additional configuration options such as:
- Volume scheduling for dynamic provisioning
- Volume resizing
- Volume snapshotting
This change includes addition of Custom resources (CRDs) pertaining to Volume snapshots. The following [CRDs](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/deploy/kubernetes/cluster/crd_snapshotter.yaml) are added as part of the component update:
- VolumeSnapshotClasses
- VolumeSnapshotContents
- VolumeSnapshots
```
kubectl apply -f https://raw.githubusercontent.com/kinvolk/lokomotive/master/assets/charts/components/aws-ebs-csi-driver/crds/snapshotter.yaml
lokoctl component apply aws-ebs-csi-driver

aws-ebs-csi-driver: add dynamic provisioning, resizing, snapshot options

---

assets/charts/control-plane/calico-host-protection/templates/host-endpoint-controller.yaml
assets/charts/control-plane/calico-host-protection/templates/psp.yaml
test/platform/packet/packet_test.go

Calico host endpoint controller only needs to talk to the apiserver and
should not be granted privileged PSP.
Update deprecated apiVersion for clusterrole and clusterrolebinding.
closes: #287

calico-host-protection: add psp rule

---

cli/cmd/cluster/apply.go

AKS does not need to ensure checking of control components as we mark it
as managed service.
closes: #1303

AKS: Don't check control plane components

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/azure/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/controller/templates/etcd.yaml.tmpl
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl

Closes #1293 
Changelog looks safe - https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md
build and provision cluster on supported platform
provision bare-metal cluster on libvirt, etcd starts up ok.
```
Jan 10 04:49:20 k8s-m-amd64-00.k8s.example.com sh[1069]: Status: Downloaded newer image for quay.io/coreos/etcd:v3.4.14
Jan 10 04:49:24 k8s-m-amd64-00.k8s.example.com sh[1069]: 9a7cff99dbf2aad5e95cb6722d00c094861c6d69967b5e1c3f91288a6eb4c285
Jan 10 04:49:27 k8s-m-amd64-00.k8s.example.com systemd[1]: Started etcd (System Application Container).
<snip>
```

etcd - update image to 3.4.14

---

docs/RELEASING.md

- Fix formatting, making it easy to copy paste the commands.
- Don't push all the tags.
- Add goreleaser download instruction.

Fix the releasing docs

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/azure/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/controller/templates/etcd.yaml.tmpl
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
docs/how-to-guides/update-etcd.md
scripts/find-updates.sh
test/system/etcd_env_vars_test.go

Closes #1065 
etcd parses all environment variables beginning with `ETCD_` by default and warns if any variables matching this pattern exist that it doesn't explicitly support.
This PR drops the `ETCD_` prefix for custom environment variables and group these vars together at top of file.
There doesn't appear to be any variable collisions in the files with the new names. For example, `kubelet` env vars are prefixed `KUBELET_`.
- build PR
- provision lokomotive on any supported platform
Provision Lokomotive using bare-metal guide on libvirt host.
Wait for etcd to start up and check logs for warnings, finding none.
Log output:
```
Jan 10 03:27:03 k8s-m-amd64-00.k8s.example.com sh[1070]: Status: Downloaded newer image for quay.io/coreos/etcd:v3.4.13
Jan 10 03:27:11 …
```

etcd - ETCD_ env var prefix for standard vars only

---

docs/quickstarts/aks.md

AKS currently provides 1.18 (and other platforms 1.19). It's easy that
this note gets out of date so let's rephrase it so it's more generic.

docs/quickstarts/aks: rephrase Kubernetes version note

---

assets/terraform-modules/packet/flatcar-linux/kubernetes/versions.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/versions.tf
pkg/platform/packet/template.go

With recent Equinix Metal API changes, `v3.0.1` of the provider can not properly detect the network type configuration for `n2.xlarge.86` devices.
`v3.2.1` does not have this problem.
Add the following worker pool to the packet cluster config and it should create the cluster without failing with issues like: `Strange 2-bond ports conf - bond0: layer3, bond1: layer2-bonded`.
```tf
worker_pool "scylla" {
count = 1
node_type = "n2.xlarge.x86"
disable_bgp = true
}
```
This is based on the work by @displague from https://github.com/kinvolk/lokomotive/pull/1347. I just ran `make install` to add all the updated assets shipped with the binary.

packet: update terraform provider to 3.2.1

---

docs/configuration-reference/components/velero.md
pkg/components/internal/testutil/jsonpath.go
pkg/components/util/types.go
pkg/components/util/types_test.go
pkg/components/velero/component_test.go
pkg/components/velero/restic/restic.go
pkg/components/velero/restic/restic_test.go

This PR fixes the issue with Restic.Tolerations; adds unit tests and fixes docs formatting.
- json tag `toleration_seconds` is changed to `tolerationSeconds`
- `TolerationSeconds` field is now an integer instead of string.
- Conditional checks added to ensure if `TolerationSeconds` is set, then `Effect` must be `NoExecute`.
- Adds unit tests
- Fixes formatting of Velero component reference documentation.

Restic bug fixes; unit tests and docs formatting

---

CHANGELOG.md
docs/installer/lokoctl.md
pkg/version/version.go
scripts/update/0.6.0-0.6.1/cluster.sh
scripts/update/0.6.0-0.6.1/update.sh

PR for Lokomotive 0.6.1 release.

Release v0.6.1

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/azure/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/azure/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/worker.yaml.tmpl
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/node/templates/node.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl

This PR adds `Restart=on-failure` and `RestartSec=5s` to the metadata service.
Fixes https://github.com/kinvolk/lokomotive/issues/1298
---
The other services which have `Type=oneshot` are following: `wait-for-dns`, `bootkube`, `delete-node`, `create-etcd-config`, `persist-data-raid`.
Most of them are the type of services which we want them to fail early and the user know about it, instead of them endlessly trying and someone else doing a time out on them.

EM: Add restart on-failure for metadata service

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/controller/templates/etcd.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
docs/how-to-guides/update-etcd.md

The rkt-based etcd-member service that is part of Flatcar used a unit
drop-in file but the new etcd service uses an environment file and
requires the folder to be set up with certain permissions.
With these changes it works again to recreate a controller node in an HA control plane cluster.
Changes were not done for baremetal because they are part of https://github.com/kinvolk/lokomotive/pull/1333 already.
Fixes https://github.com/kinvolk/lokomotive/issues/1381

Fix wrong etcd settings

---

examples/packet-testing/cluster.lokocfg

EM config shows management_cidrs as a string when it is a list of
string.

examples: Fix EM config

---

docs/how-to-guides/auto-update-flatcar.md

docs: Use FLUO to update nodes

---

assets/charts/components/node-problem-detector/Chart.yaml
assets/charts/components/node-problem-detector/README.md
assets/charts/components/node-problem-detector/templates/NOTES.txt
assets/charts/components/node-problem-detector/templates/_helpers.tpl
assets/charts/components/node-problem-detector/templates/clusterrole.yaml
assets/charts/components/node-problem-detector/templates/clusterrolebinding.yaml
assets/charts/components/node-problem-detector/templates/custom-config-configmap.yaml
assets/charts/components/node-problem-detector/templates/daemonset.yaml
assets/charts/components/node-problem-detector/templates/psp-clusterrole.yaml
assets/charts/components/node-problem-detector/templates/psp-clusterrolebinding.yaml
assets/charts/components/node-problem-detector/templates/psp.yaml
assets/charts/components/node-problem-detector/templates/service.yaml
assets/charts/components/node-problem-detector/templates/serviceaccount.yaml
assets/charts/components/node-problem-detector/templates/servicemonitor.yaml
assets/charts/components/node-problem-detector/values.yaml
ci/aks/aks-cluster.lokocfg.envsubst
ci/aws/aws-cluster.lokocfg.envsubst
ci/baremetal/baremetal-cluster.lokocfg.envsubst
ci/packet/packet-cluster.lokocfg.envsubst
cli/cmd/cluster/component.go
docs/concepts/components.md
docs/configuration-reference/components/node-problem-detector.md
pkg/components/node-problem-detector/component.go
pkg/components/node-problem-detector/component_test.go
pkg/components/node-problem-detector/doc.go
pkg/components/node-problem-detector/template.go
test/components/node-problem-detector/nodeproblemdetector_test.go
test/monitoring/components_metrics_test.go

This adds component node-problem-detector. For more information
refer to https://github.com/kubernetes/node-problem-detector.
closes: #39
Pass the following in your cluster config. To use `service_monitor` feature, make sure [Prometheus Operator](https://kinvolk.io/docs/lokomotive/0.6/configuration-reference/components/prometheus-operator/) component is installed
```bash
component "node-problem-detector" {
service_monitor = true
}
```

Add component node-problem-detector

---

assets/terraform-modules/packet/flatcar-linux/kubernetes/bootkube.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/calico-host-protection.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/variables.tf
ci/packet/packet-cluster.lokocfg.envsubst
ci/packet_arm/packet_arm-cluster.lokocfg.envsubst
ci/packet_fluo/packet_fluo-cluster.lokocfg.envsubst
cli/cmd/cluster/cluster.go
cli/cmd/cluster/utils_internal_test.go
docs/configuration-reference/platforms/baremetal.md
docs/configuration-reference/platforms/packet.md
docs/quickstarts/packet.md
examples/packet-production/cluster.lokocfg
examples/packet-testing/cluster.lokocfg
go.mod
pkg/platform/packet/packet.go
pkg/platform/packet/packet_test.go
pkg/platform/packet/template.go
vendor/modules.txt

This commit adds a param to the worker pools called facility. This
allows users to choose a different facility/region than the controller
nodes. The default behaviour is to deploy controllers and workers in the
same facility.
Signed-off-by: Suraj Deshmukh <suraj@kinvolk.io>

EM: Add worker pool specific facility param

---

docs/how-to-guides/worker-pool-separate-facility.md

This commit adds a doc that shows how to add a new worker pool to a
separate facility than the control plane and other worker pools.

docs: How to add worker pool to separate facility

---

assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl

This commit adds `RemainAfterExit=true` to metadata service. Other
services of type `oneshot` already have it.
Fixes: #1371

EM: Add remain RemainAfterExit to metadata service

---

docs/quickstarts/aws.md

docs/quickstart: Refactor AWS guide

---

assets/charts/components/contour/templates/03-envoy.yaml
pkg/components/aws-ebs-csi-driver/component_test.go
pkg/components/contour/component_test.go
pkg/components/internal/testutil/common.go
pkg/components/internal/testutil/jsonpath.go
pkg/components/istio-operator/component_test.go
pkg/components/node-problem-detector/component_test.go
pkg/components/prometheus-operator/component_test.go
pkg/components/velero/component_test.go
pkg/k8sutil/create.go
pkg/k8sutil/create_test.go

This change was introduced in 8d44c8513f67512527218c8a538e79a61cb7cd34 - "don't expose Envoy using hostPorts". But a later commit overrode it: 6a6a3c5d849b981559c2cc2cf3797bfd6b6c9159 - "contour: Update to v1.7.0". This commit fixes this regression.
Fixes: https://github.com/kinvolk/lokomotive/issues/1336

contour: Fix the hostPort regression

---

pkg/components/util/helm.go
pkg/components/util/helm_internal_test.go
pkg/components/util/helm_test.go

With existing implementation, if there is more than one hook defined in
a single file, last hook will overwrite the previous one when rendering,
as we index hooks using Path and 2 hooks will have the same path.
CRDs are not affected, as we index them by name and there should be no
duplicate CRDs in chart defined.
Closes #1345

pkg/components/util: retain all hooks from a single file while rendering

---

.goreleaser.yml
docs/quickstarts/packet.md
docs/quickstarts/tinkerbell.md

This PR ensures the version string printed by `lokoctl version` is consistent for binaries created using `make` and binaries created as part of the release process.
The GitHub URIs for released binaries are updated accordingly as well.
Fixes #1150.
To test the PR, create a fake Git tag, create a release without publishing it and ensure the printed version string has a "v":
```
git tag v0.7.0-test
goreleaser release --skip-publish --skip-sign
./dist/lokoctl_linux_amd64/lokoctl version
```

Include a "v" in version strings when releasing

---

assets/terraform-modules/platforms/tinkerbell/workerpool/main.tf

This commit fixes a regression that came about when `cluster_name`
variable was added to the generic `worker` module in this commit
ee39dabb7a2a5fe4f1a5035d2284756e6d84ce22.
Since it is a required variable, tinkerbell ci failed.
This commit fixes the above issue, by passing the `cluster_name` to the
worker module.
Failed CI build : https://yard.lokomotive-k8s.net/teams/main/pipelines/master-tinkerbell/jobs/test-lokomotive-deployment/builds/43

tinkerbell: pass cluster_name to worker module

---

docs/installer/lokoctl.md

Add a missing "v" in the installation guide which became necessary following https://github.com/kinvolk/lokomotive/pull/1417.
While this won't fix the docs for `v0.7.0`, it will help in the next releases.

docs/installer/lokoctl.md: Add missing "v"

---

README.md

The old URL is deprecated and
https://landscape.cncf.io/?selected=lokomotive should be used instead.
Click on the logo and check that not deprecated URL message is shown in the CNCF landscape site.

Update certified Kubernetes logo target URL

---

.github/workflows/ci.yaml
Dockerfile
Makefile
cmd/admission-webhook-server/Dockerfile

With this the golang version need only be set in the Makefile, then it
trickles into the container builds.
Starting it off at go1.15.10
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
* `make build-in-docker`
* `make docker-build`
* `make docker-build-webhook`
For testing, you could even pass an alternate version to make: 
```shell
vbatts@melisma:~/src/github.com/kinvolk/lokomotive$ make docker-build GOLANG_VERSION=1.16.2
docker build -t kinvolk/lokomotive --build-arg GOLANG_VERSION=1.16.2 .
Sending build context to Docker daemon  230.1MB
Step 1/5 : ARG GOLANG_VERSION=1.15.10
Step 2/5 : FROM golang:${GOLANG_VERSION}
1.16.2: Pulling from library/golang
Digest: sha256:3c4d8b77baf3e12b4a1f08a99bf248f8be125045b4448455884a16e977907f11
Status: Downloaded newer image for golang:1.16.2
---> …
```

align the golang version used

---

assets/charts/components/dex/templates/deployment.yaml

This uses the latest alpine/git image to deploy Dex. This release added
ARM64 support which stops Dex from breaking when deploying it on ARM64.
Install Dex in an ARM64 cluster
Tested on Raspberry Pi

Use new version of apline/git in Dex

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/versions.tf
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/versions.tf
assets/terraform-modules/azure/flatcar-linux/kubernetes/versions.tf
assets/terraform-modules/azure/flatcar-linux/kubernetes/workers/versions.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/versions.tf
assets/terraform-modules/bootkube/versions.tf
assets/terraform-modules/controller/versions.tf
assets/terraform-modules/dns/route53/versions.tf
assets/terraform-modules/node/versions.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/versions.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/versions.tf
assets/terraform-modules/tinkerbell-sandbox/versions.tf
assets/terraform-modules/worker/versions.tf
pkg/platform/aks/template.go
scripts/find-updates.sh

This updates all Terraform providers which we use to the latest versions.
It also adds 2 bootkube dependancies to the find updates script.
Successfully apply a cluster
Working on testing, first waiting on the e2e to do some obvious catches

Update Terraform providers

---

docs/configuration-reference/components/cert-manager.md
pkg/components/cert-manager/component.go

This removes the webhook flag from the cert-manager component as it did not function any longer. The no webhook version no longer exists.
- install cert-manager
- Checked creation of fresh cluster
- Checked when upgrading from 0.6.1 to this commit
~~So removing the HCL flag might need some upgrade path, keeping it draft for now till I worked that out :) Just a quick patch in between other work.~~
As discussed in Slack removing the flag is fine pre-1.0 , should be released in a new minor release with a note however.

Remove the Webhook setting of cert-manager

---

docs/configuration-reference/components/metallb.md

- Fix duplicated `Lokomotive` in docs about MetalLB configuration
https://kinvolk.io/docs/lokomotive/0.5/configuration-reference/components/metallb/

Fix typo in docs

---

pkg/platform/baremetal/baremetal.go

In order to limit the number of cnocurrent operations as Terraform walks
the graph, `-parallelism=n` is used, with a default value of 10.
When rotating certificates, it is desirable to limit parallelism to `1`,
so that certificates are rotated one by one and we still have quorum.
In baremtal platform, there is a case of missing hiphen before
`parallelism`:
```
current - return ex.Apply([]string{"parallelism=1"})
correct - return ex.Apply([]string{"-parallelism=1"})
```
Hence the following error:
```
stat parallelism=1: no such file or directory
```
This commit provides the fix by correcting the code in question.

baremetal: fix terraform non-parallel execution

---

cli/cmd/cluster-apply.go
cli/cmd/cluster/apply.go
docs/cli/lokoctl_cluster_apply.md

When the cluster is not fully set up and lokoctl is run again to fix that
problem, the user may want to avoid the control plane update happen at the
same time, because it can cause issues.
This PR is in a series of multiple PRs that will be created to ease the review/acceptance/merge of a large PR #1402

cli/cmd/cluster: allow to skip the control plane update

---

assets/terraform-modules/tinkerbell-sandbox/assets/deploy/tls/Dockerfile

`cfssl` package for alpine has been removed. Hence the build fails. This
commit moves to a fedora based image.

tinkerbell: Move to fedora based image

---

pkg/components/rook/component.go

Tihs is causing codespell to fail.

typo: fix typo

---

ci/packet_arm/packet_arm-cluster.lokocfg.envsubst
docs/configuration-reference/platforms/packet.md

HTTPs with iPXE is unreliable and fails to download the content with
errors like:
```
https://alpha.release.flatcar-linux.net/arm64-usr/current/flatcar_production_packet.ipxe... Invalid argument (http://ipxe.org/1c0de882)
Could not boot image: Invalid argument (http://ipxe.org/1c0de882)
No more network devices
```
So this commit switches from HTTPs to HTTP.

EM ARM: Use HTTP for iPXE URL

---

assets/terraform-modules/matchbox-flatcar/templates/install.yaml.tmpl

In case the network only has a temporary problem, the installer service
should start again on failure.
Convert it to a oneshot service to set RemainAfterExist, so that it is
not triggered twice if anything that depends on it is pulling it in
again after it finished.

baremetal: let installer.service retry on failure

---

assets/charts/components/dex/templates/deployment.yaml
assets/charts/control-plane/kube-apiserver/Chart.yaml
assets/charts/control-plane/kube-apiserver/values.yaml
assets/charts/control-plane/kubelet/Chart.yaml
assets/charts/control-plane/kubelet/container-image/Dockerfile
assets/charts/control-plane/kubelet/values.yaml
assets/charts/control-plane/kubernetes/Chart.yaml
assets/charts/control-plane/kubernetes/values.yaml
assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/azure/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/azure/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/bootkube/variables.tf
assets/terraform-modules/controller/variables.tf
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/node/variables.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/worker/variables.tf
docs/how-to-guides/troubleshoot-openebs.md

Release Notes:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md
---
**Notes for upcoming release**
- Release should include a script that updates bootstrap kubelet version.

k8s: Update to v1.21.1

---

assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/controller.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/worker.tf
test/components/kubernetes/baremetal_kubelet_labels_test.go

Sets the hostname from the `<cluster_name>-worker-<count_index>` which
is set when `set_standard_hostname` is true, to
`controller_names<count_index>` for controllers and
`worker_names<count_index>` for workers

baremetal: sets hostname controller_names/worker_names

---

pkg/platform/aks/aks.go
pkg/platform/aws/aws.go
pkg/platform/baremetal/baremetal.go
pkg/platform/packet/packet.go
pkg/platform/tinkerbell/tinkerbell.go
pkg/terraform/executor.go

The default of 10 parallel steps does not limit creation of a small cluster but on a cluster with more than 10 nodes it leads to creation in sequential batches of 10, slowing the bring up down.
This PR is in a series of multiple PRs that will be created to ease the review/acceptance/merge of a large PR #1402

pkg/terraform: increase the default parallelism

---

assets/charts/components/dex/Chart.yaml
assets/charts/components/dex/templates/clusterrole.yaml
assets/charts/components/dex/templates/clusterrolebinding.yaml
assets/charts/components/dex/templates/deployment.yaml
assets/charts/components/dex/templates/ingress.yaml

Release Notes: https://github.com/dexidp/dex/releases/tag/v2.28.1

dex: Update to v2.28.1

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/platforms/tinkerbell/controllers/ssh.tf

We observed CI failures when restarting etcd after copying its
certificates. This prints logs when restarting fails which is
interesting in general.

cert-rotation: print journal on error when restarting etcd

---

docs/how-to-guides/rook-ceph-storage.md

In 07c493da303266579b39cd231aa9085bb8d2a40e and
221249dcad626f8e68625c60ed1682d8668d321e we changed the syntax of labels
and taints to a map.
This changes the Rook Ceph how to guide to use the new format.

docs/howto/rook-ceph: use new label syntax

---

assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/controller_profiles.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/variables.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/worker_profiles.tf
assets/terraform-modules/matchbox-flatcar/profiles.tf
assets/terraform-modules/matchbox-flatcar/templates/install.yaml.tmpl
assets/terraform-modules/matchbox-flatcar/variables.tf
docs/configuration-reference/platforms/baremetal.md
pkg/platform/baremetal/baremetal.go
pkg/platform/baremetal/template.go

This PR disables LVM partitions so that any detected LVM partitions are not automatically 
activated on bootup disrupting the installation and wipes any additional disks attached to the
machine before proceeeding 
This PR is in a series of multiple PRs that will be created to ease the review/acceptance/merge of a large PR #1402

baremetal disable lvm mappings wipe additional disks

---

assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/controller.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/controller_profiles.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/variables.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/worker.tf
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/worker_profiles.tf
assets/terraform-modules/matchbox-flatcar/profiles.tf
assets/terraform-modules/matchbox-flatcar/pxe-helper.sh.tmpl
assets/terraform-modules/matchbox-flatcar/ssh.tf
assets/terraform-modules/matchbox-flatcar/templates/install.yaml.tmpl
assets/terraform-modules/matchbox-flatcar/variables.tf
assets/terraform-modules/matchbox-flatcar/versions.tf
ci/baremetal/baremetal-cluster.lokocfg.envsubst
docs/configuration-reference/platforms/baremetal.md
docs/quickstarts/baremetal.md
pkg/platform/baremetal/baremetal.go
pkg/platform/baremetal/template.go

-  baremetal: introduce CLC snippets for the installer    
The installer OS needs to be able to get its network configuration as
CLC snippet if DHCP is not used.
Add CLC snippets for the installer and migrate the matchbox-specific
CLC template to the normal CLC template which is needed for CLC
snippets. The request template variable is replaced by the actually
used "mac" parameter.
- baremetal: use ignition.config.url kernel parameter
The Ignition configuration currently gets written out only once to the
OEM partition and any updates to it in the matchbox store are not
propagated to the node's Ignition environment when Ignition is forced
to run again.
Use the Ignition kernel parameter to point the node's Ignition
environment directly to matchbox where the userdata lies.
- baremetal: …

baremetal: integrate automated (re-)provisioning logic

---

ci/aws/aws-cluster.lokocfg.envsubst

AWS CI keeps failing on cert-rotation test because apiserver takes a
really long time to come back up.
It is possible that the failure rate on AWS is higher because the
machine type on AWS is tiny which is unable to sustain the load
generated due to control plane component restarts.
This commit upgrades the control plane machine to fairly larger one.

aws ci: Use c5a.2xlarge for controllers

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/aws/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/controller/templates/etcd.yaml.tmpl
assets/terraform-modules/node/templates/node.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/ssh.tf
assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
assets/terraform-modules/platforms/tinkerbell/controllers/ssh.tf

- Only restart containers from systemd
Restarting etcd or the kubelet container from the Docker daemon
introduces a race because the "docker logs" command will terminate and
then the systemd unit will also restart the container in parallel to
the Docker daemon. This race causes problems like terminating the
container again or failing to start it, but it also introduces
additional issues because the ExecStartPre and ExecStopPost commands
run while the container is running, which means the state can get
corrupted. Even if the systemd unit would not restart in parallel, it
is not wanted to restart the container from the Docker daemon because
the systemd unit should first run the ExecStartPre/Post commands, e.g.,
for the "etcd-rejoin" script.
Only restart the containers from the systemd unit, …

Only restart containers from systemd

---

assets/charts/components/node-problem-detector/.helmignore
assets/charts/components/node-problem-detector/Chart.yaml
assets/charts/components/node-problem-detector/README.md
assets/charts/components/node-problem-detector/templates/_helpers.tpl
assets/charts/components/node-problem-detector/templates/daemonset.yaml
assets/charts/components/node-problem-detector/templates/servicemonitor.yaml
assets/charts/components/node-problem-detector/values.yaml
docs/development/updating-components.md

Release notes: https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.8

Update node-problem-detector to v0.8.8

---

assets/charts/components/rook/Chart.yaml
assets/charts/components/rook/dashboards/ceph-cluster.json
assets/charts/components/rook/dashboards/ceph-osd.json
assets/charts/components/rook/dashboards/ceph-pools.json
assets/charts/components/rook/templates/NOTES.txt
assets/charts/components/rook/templates/clusterrole.yaml
assets/charts/components/rook/templates/clusterrolebinding.yaml
assets/charts/components/rook/templates/deployment.yaml
assets/charts/components/rook/templates/psp.yaml
assets/charts/components/rook/templates/resources.yaml
assets/charts/components/rook/templates/role.yaml
assets/charts/components/rook/templates/rolebinding.yaml
assets/charts/components/rook/templates/serviceaccount.yaml
assets/charts/components/rook/values.yaml
docs/development/updating-components.md
docs/how-to-guides/update-rook-ceph.md
pkg/components/rook-ceph/manifests.go
pkg/components/rook/manifests.go

Fixes https://github.com/kinvolk/lokomotive/issues/1494

Update rook to v1.6.5

---

cli/cmd/cluster/cluster.go
pkg/helm/history.go
pkg/helm/history_test.go

We expect to get the history in descending order by version and limited
to 1 version to get the last version so we can ensure the user has the
last version of the Helm chart.
However, it turns out the Helm API doesn't honor the Max config parameter and
returns the Helm history in a non-deterministic order.
This adds a wrapper function that sorts what the Helm API returns in the
way we expect and uses that.
Fixes #1442

pkg/helm: add wrapper to get the Helm history we expect

---

assets/charts/components/contour/Chart.yaml
assets/charts/components/contour/crds/01-crds.yaml
assets/charts/components/contour/templates/01-contour-config.yaml
assets/charts/components/contour/templates/02-job-certgen.yaml
assets/charts/components/contour/templates/02-role-contour.yaml
assets/charts/components/contour/templates/02-service-envoy.yaml
assets/charts/components/contour/templates/03-contour.yaml
assets/charts/components/contour/templates/03-envoy.yaml
assets/charts/components/contour/values.yaml
pkg/platform/aks/aks.go
test/components/kubernetes/namespaces_labels_test.go

Release Notes:
https://github.com/projectcontour/contour/releases/tag/v1.16.0.
---
Update
```
kubectl apply -f https://raw.githubusercontent.com/projectcontour/contour/v1.16.0/examples/contour/01-crds.yaml
lokoctl component apply contour
```

contour: Update to v1.16.0

---

assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
assets/terraform-modules/controller/main.tf
assets/terraform-modules/controller/templates/etcd.yaml.tmpl
assets/terraform-modules/node/templates/node.yaml.tmpl
assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl

Over time we've added ConditionPathExists= parameters to several unit
files. However, in some instances we were adding them in the [Service]
section instead of the [Unit] section. This meant they were ignored and
didn't have any effect.
This moves those conditions to the [Unit] section everywhere.
Fixes #1066

terraform: fix ignored ConditionPathExists= in unit files

---

assets/charts/control-plane/calico/Chart.yaml
assets/charts/control-plane/calico/scripts/README.md
assets/charts/control-plane/calico/scripts/calico-images.sh
assets/charts/control-plane/calico/values.yaml
assets/terraform-modules/bootkube/variables.tf

Release Notes:
https://docs.projectcalico.org/archive/v3.19/release-notes/

calico: Update to v3.19.1

---

cli/cmd/cluster/apply.go
cli/cmd/cluster/certificate-rotator.go
cli/cmd/cluster/cluster.go

It was being ignored and kubelets were being upgraded no matter what.
Fixes #1480

cluster/apply: honor --upgrade-kubelets

---

assets/charts/components/azure-arc-onboarding/Chart.yaml
assets/charts/components/azure-arc-onboarding/templates/_helpers.tpl
assets/charts/components/azure-arc-onboarding/templates/rbac.yaml
assets/charts/components/azure-arc-onboarding/templates/register.yaml
assets/charts/components/azure-arc-onboarding/templates/remove.yaml
assets/charts/components/azure-arc-onboarding/templates/secret.yaml
assets/charts/components/azure-arc-onboarding/templates/serviceaccount.yaml
assets/charts/components/azure-arc-onboarding/values.yaml
cli/cmd/cluster/component.go
docs/configuration-reference/components/azure-arc-onboarding.md
docs/how-to-guides/gitops-using-azure-arc-onboarding-component.md
pkg/components/azure-arc-onboarding/component.go
pkg/components/azure-arc-onboarding/component_test.go
pkg/components/azure-arc-onboarding/image/Dockerfile
pkg/components/azure-arc-onboarding/image/azure-arc.sh
pkg/components/azure-arc-onboarding/template.go

This PR adds a new Lokomotive component `azure-arc-lokomotive` for onboarding and removing a Lokomotive cluster from Azure Arc.
To test:
follow the configuration reference documentation for the component.
```
component azure-arc-lokomotive {
application_client_id=""
tenant_id=""
application_password=""
resource_group=""
cluster_name=""
}
```
```
lokoctl component apply azure-arc-onboarding
```

Lokomotive component azure-arc-onboarding

---

docs/how-to-guides/backup-rook-ceph-volumes.md

This add information about restic parameter `require_volume_annotation`.
It is set to false by default and all the volumes are backed up without
need for annotation.
closes: #1519

how-to-docs: require_volume_annotation information

---

pkg/components/azure-arc-onboarding/component_test.go

Declaring the component config outside made the azure-arc-onboarding
component's unit tests flaky.
This commit fixes the flakiness.

test: fix azure-arc-onboarding unit test flakiness

---

cli/cmd/cluster-apply.go
docs/cli/lokoctl_cluster_apply.md

It has been tested enough and it works reliably.
Fixes #110

cluster/apply: enable upgrade kubelets by default

---

assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl

This label has been added to match the OEM partition.
This label has been added to match the OEM partition. This addition is needed after the following change in ignition: https://github.com/kinvolk/ignition/commit/1c735118f7091f6b22d10945bf3b5fdf9e50dbee.

packet: Add OEM partition label

---

cli/cmd/cluster/cluster.go

Defining the `MaxHistory` option during the rollback Helm action so that
the releases history is cleaned up accordingly.
Without this option the history would never been cleared which is
accumulating old configuration which can be harmful when a incorrect
rollback is applied. By cleaning up the history, we limit the potential
impact rolling back to a older version.

feat: define MaxHistory for Helm releases

---

assets/charts/components/openebs-storage-class/.helmignore
assets/charts/components/openebs-storage-class/Chart.yaml
assets/charts/components/openebs-storage-class/templates/storage-class.yaml
assets/charts/components/openebs-storage-class/values.yaml
pkg/components/openebs-storage-class/component.go
pkg/components/openebs-storage-class/component_test.go
pkg/components/openebs-storage-class/template.go

Signed-off-by: Suraj Deshmukh <suraj@kinvolk.io>
Part of #1528 
Also look into https://github.com/kinvolk/lokomotive/pull/1557#issuecomment-908091304

openebs-storage-class: Move to Helm Chart

---

assets/charts/components/prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml
pkg/components/prometheus-operator/template.go

This commit fixes the repeated `annotations` in the PSP config. Existing
config has `annotations` defined once outside the `{{- if .. }}` block
and again inside it. So if a user defines the `annotations` value in the
values file then in end the PSP has two `annotations` block.

prometheus-operator: Fix the repeated annotations

---

assets/terraform-modules/tinkerbell-sandbox/assets/deploy/flatcar-install/Dockerfile

This commit adds additional packages which are required in the
`flatcar-install` script.

tinkerbell: Add btrfs-progs and gawk to Dockerfile

---

go.mod
go.sum
vendor/github.com/gogo/protobuf/proto/text_parser.go
vendor/golang.org/x/sync/semaphore/semaphore.go
vendor/modules.txt

Update `github.com/gogo/protobuf` to `v1.3.2` mainly to address [CVE-2021-3121](https://nvd.nist.gov/vuln/detail/CVE-2021-3121).

go: update github.com/gogo/protobuf to v1.3.2
