- test/components/cert-manager/cert-manager_test.go
- test/components/cluster-autoscaler/cluster-autoscaler_test.go
- test/components/contour/contour_test.go
- test/components/coredns/coredns_test.go
- test/components/dex/dex_test.go
- test/components/external-dns/external-dns_test.go
- test/components/flatcar-linux-update-operator/fluo_test.go
- test/components/gangway/gangway_test.go
- test/components/httpbin/httpbin_test.go
- test/components/kubernetes/controller-manager_test.go
- test/components/metallb/metallb_test.go
- test/components/metrics-server/metrics_server_test.go
- test/components/openebs-operator/openebs_operator_test.go
- test/components/prometheus-operator/prometheus_operator_test.go
- test/components/rook/rook_test.go
- test/components/util/util.go
Let's expect the Kubernetes expected amount of replicas and remove the
expected replicas parameter from the function.
> test: wait for expected replicas in WaitForDeployment

- cli/cmd/component-install.go
- test/components/install_test.go
> Fix some typos

- docs/configuration-guides/components/calico-hostendpoint-controller.md
- docs/configuration-guides/components/cert-manager.md
- docs/configuration-guides/components/cluster-autoscaler.md
- docs/configuration-guides/components/contour.md
- docs/configuration-guides/components/dex.md
- docs/configuration-guides/components/external-dns.md
- docs/configuration-guides/components/flatcar-linux-update-operator.md
- docs/configuration-guides/components/gangway.md
- docs/configuration-guides/components/metallb.md
- docs/configuration-guides/components/metrics-server.md
- docs/configuration-guides/components/openebs-operator.md
- docs/configuration-guides/components/openebs-storage-class.md
- docs/configuration-guides/components/prometheus-operator.md
- docs/configuration-guides/components/rook-ceph.md
- docs/configuration-guides/components/rook.md
- docs/configuration-guides/components/velero.md
> Rewording "Uninstallation" to "Uninstalling" in component configuration guides

- ci/packet-arm/packet-arm-cluster.lokocfg.envsubst
See https://github.com/kinvolk/lokomotive-ci/pull/97 for details.
> ci/packet-arm: allow facility to be substituted

- docs/installer/packet.md
Signed-off-by: Rodrigo Campos <rodrigo@kinvolk.io>
> docs/packet: Add link on how to enable Local BGP

- docs/configuration-guides/components/calico-hostendpoint-controller.md
- docs/configuration-guides/components/cert-manager.md
- docs/configuration-guides/components/cluster-autoscaler.md
- docs/configuration-guides/components/contour.md
- docs/configuration-guides/components/dex.md
- docs/configuration-guides/components/external-dns.md
- docs/configuration-guides/components/flatcar-linux-update-operator.md
- docs/configuration-guides/components/gangway.md
- docs/configuration-guides/components/metallb.md
- docs/configuration-guides/components/metrics-server.md
- docs/configuration-guides/components/openebs-operator.md
- docs/configuration-guides/components/openebs-storage-class.md
- docs/configuration-guides/components/prometheus-operator.md
- docs/configuration-guides/components/rook-ceph.md
- docs/configuration-guides/components/rook.md
- docs/configuration-guides/components/velero.md
> Changing heading from Installation to Installing.

- docs/installer/lokoctl.md
> lokoctl installation document

- docs/configuration-guides/platforms/baremetal.md
> Platform configuration guide for Bare Metal.

- pkg/components/metallb/manifests.go
Current Dashboard: https://snapshot.raintank.io/dashboard/snapshot/u0e7rPm1wAM7C8Ky222ol5t8xS633Z90
> metallb: Add grafana dashboard

- Dockerfile
- Makefile
- README.md
- docs/CONTRIBUTING.md
- docs/concepts/components.md
- docs/images/lokomotive-logo.svg
Check commit messages for details.
There's probably more things to fix but this is a first step.
Closes #51
> docs: rework README and several other docs fixes

- examples/packet-production/cluster.lokocfg
- examples/packet-testing/cluster.lokocfg
Without this metallb fails to install.
Fixes #97
> examples/packet: add metallb_address_pool variable

- docs/configuration-reference/backend/local.md
- docs/configuration-reference/backend/s3.md
- docs/configuration-reference/components/calico-hostendpoint-controller.md
- docs/configuration-reference/components/cert-manager.md
- docs/configuration-reference/components/cluster-autoscaler.md
- docs/configuration-reference/components/contour.md
- docs/configuration-reference/components/dex.md
- docs/configuration-reference/components/external-dns.md
- docs/configuration-reference/components/flatcar-linux-update-operator.md
- docs/configuration-reference/components/gangway.md
- docs/configuration-reference/components/metallb.md
- docs/configuration-reference/components/metrics-server.md
- docs/configuration-reference/components/openebs-operator.md
- docs/configuration-reference/components/openebs-storage-class.md
- docs/configuration-reference/components/prometheus-operator.md
- docs/configuration-reference/components/rook-ceph.md
- docs/configuration-reference/components/rook.md
- docs/configuration-reference/components/velero.md
- docs/configuration-reference/platforms/aws.md
- docs/configuration-reference/platforms/baremetal.md
- docs/configuration-reference/platforms/packet.md
- docs/quickstarts/aws.md
- docs/quickstarts/packet.md
Closes https://github.com/kinvolk/lokomotive/issues/167
> docs: small fixes

- docs/configuration-reference/components/calico-hostendpoint-controller.md
- docs/configuration-reference/components/cert-manager.md
- docs/configuration-reference/components/cluster-autoscaler.md
- docs/configuration-reference/components/contour.md
- docs/configuration-reference/components/dex.md
- docs/configuration-reference/components/external-dns.md
- docs/configuration-reference/components/flatcar-linux-update-operator.md
- docs/configuration-reference/components/gangway.md
- docs/configuration-reference/components/httpbin.md
- docs/configuration-reference/components/metallb.md
- docs/configuration-reference/components/metrics-server.md
- docs/configuration-reference/components/openebs-operator.md
- docs/configuration-reference/components/openebs-storage-class.md
- docs/configuration-reference/components/prometheus-operator.md
- docs/configuration-reference/components/rook-ceph.md
- docs/configuration-reference/components/rook.md
- docs/configuration-reference/components/velero.md
Also, change wording in component documentation.
> docs/configuration-reference: add httpbin reference 

- CHANGELOG.md
- pkg/version/version.go
> Release v0.1.0

- README.md
> Fix contributing guidelines link.

- test/monitoring/components_metrics_test.go
> test/monitoring: test that at least one metric is returned

- README.md
Follow up from https://github.com/kinvolk/lokomotive/pull/217.
> README: Update kubernetes version to 1.18

- cli/cmd/cluster-apply.go
- cli/cmd/cluster-destroy.go
- cli/cmd/cluster.go
- cli/cmd/component-apply.go
- cli/cmd/component-render-manifest.go
- cli/cmd/component.go
- cli/cmd/health.go
- cli/cmd/root.go
- cli/cmd/version.go
- docs/cli/lokoctl.md
- docs/cli/lokoctl_cluster.md
- docs/cli/lokoctl_cluster_apply.md
- docs/cli/lokoctl_cluster_destroy.md
- docs/cli/lokoctl_component.md
- docs/cli/lokoctl_component_apply.md
- docs/cli/lokoctl_component_list.md
- docs/cli/lokoctl_component_render-manifest.md
- docs/cli/lokoctl_health.md
- docs/cli/lokoctl_version.md
This PR improves the phrasing of command help in lokoctl.
> Rephrase command help

- pkg/components/dex/component.go
Release Notes: https://github.com/dexidp/dex/releases/tag/v2.23.0
> dex: Update to v2.23.0

- pkg/components/gangway/component.go
All the configs are taken from: https://github.com/heptiolabs/gangway/tree/master/docs/yaml
> gangway: Update configs to match upstream

- docs/configuration-reference/components/prometheus-operator.md
- pkg/components/prometheus-operator/component.go
- pkg/components/prometheus-operator/template.go
This adds knobs that were non-existent before.
Partially helps with https://github.com/kinvolk/lokomotive/issues/381
> prometheus-operator: Add storage class & size options

- pkg/platform/aws/template.go
- fix rendering error target_groups in worker pool.
- fix rendering error in clc_snippets in worker pool.
- fix rendering error in ssh_pub_keys in worker pool.
> Fix: Rendering of fields in AWS template.

- pkg/components/prometheus-operator/template.go
Fixes https://github.com/kinvolk/lokomotive/issues/452
> Prometheus Operator Grafana: Enable piechart plugin

- docs/quickstarts/aws.md
> docs/quickstart/aws: Fix flatcar-linux-update-operator link

- docs/RELEASING.md
- docs/concepts/components.md
- docs/configuration-reference/components/prometheus-operator.md
- docs/how-to-guides/authentication-with-dex-gangway.md
- docs/quickstarts/packet.md
This commit fixes the broken relative links in the repository.
> fix: update broken links

- pkg/platform/packet/packet.go
- pkg/platform/packet/packet_test.go
os_version only works for IPXE. Fixes #61
> Add error message for missing ipxe_script_url

- cli/cmd/component-delete.go
- docs/cli/lokoctl_component_delete.md
> Remove period (.) from flag descriptions

- cli/cmd/component-delete.go
> Fix indentation for component-delete `confirm` flag

- docs/KEYS.md
> docs/KEYS: Fix broken link to keys

- CHANGELOG.md
- pkg/version/version.go
> Release v0.2.0 (Bernina Express)

- docs/configuration-reference/components/contour.md
> Fix docs for contour to use with AWS platform

- docs/configuration-reference/backend/s3.md
- docs/quickstarts/aks.md
- docs/quickstarts/aws.md
- docs/quickstarts/baremetal.md
- docs/quickstarts/packet.md
* Provides instructions on how to set up the S3 backend
* Adds reference to backend configuration to quickstarts
> Improve Backend Documentation

- docs/KEYS.md
> keys: Add keys to the trusted keys document

- docs/configuration-reference/components/prometheus-operator.md
This PR fixes the unit of storage from `GiB` to `Gi`.
> docs prometheus-operator: Fix the storage unit

- ci/aws/aws-cluster.lokocfg.envsubst
- ci/packet/packet-cluster.lokocfg.envsubst
- pkg/components/metrics-server/component.go
- test/ingress/aws/aws_test.go
Closes #760.
Closes #762.
See commit messages for the details.
> test/ingress/aws: fix tests timeouts and run tests in parallel

- Makefile
> makefile: fix broken `make update`

- scripts/find-updates.sh
This commit checks updates for prometheus-operator, rook, velero,
aws-ebs-csi-driver, cluster-autoscaler.
> scripts/find updates: Add more components

- .golangci.yml
- Makefile
> Add golangci-lint config file

- cli/cmd/cluster-apply.go
- cli/cmd/health.go
- pkg/lokomotive/cluster.go
> pkg/lokomotive: make NewCluster to not return error

- scripts/find-updates.sh
Original repo has been archived and moved to packethost/terraform-provider-packet
> Fix script for Packet Provider

- scripts/find-updates.sh
To be merged after #859 
Closes #809
> Add cluster-autoscaler update check

- assets/charts/components/gangway/.helmignore
- assets/charts/components/gangway/Chart.yaml
- assets/charts/components/gangway/templates/configmap.yaml
- assets/charts/components/gangway/templates/deployment.yaml
- assets/charts/components/gangway/templates/ingress.yaml
- assets/charts/components/gangway/templates/secret.yaml
- assets/charts/components/gangway/templates/service.yaml
- assets/charts/components/gangway/values.yaml
- pkg/components/gangway/component.go
- pkg/components/gangway/component_test.go
- pkg/components/gangway/template.go
- pkg/components/httpbin/component_test.go
> gangway update helm chart

- docs/configuration-reference/platforms/baremetal.md
- pkg/platform/baremetal/baremetal.go
- pkg/platform/baremetal/template.go
Add docs for baremetal
Closes: #976
> Expose CNI MTU on the baremetal platform

- pkg/platform/platform.go
> pkg/platform: fix imports order

- pkg/components/components.go
> pkg/components: remove unused List() function

- pkg/assets/assets_generate.go
> pkg/asssets/assets_generate: Fix copyright

- .golangci.yml
> .golangci.yml: Re-enable linters

- scripts/find-updates.sh
Some charts were moved to assets directory.
Add httpbin and fluo updates check
TLS provider is removed from packet so fixed that too.
closes: #1033
> Fix scripts/find-updates..sh

- test/components/kubernetes/kubelet_disruptive_test.go
Re-starting the pod will immidiately trigger re-adding the node, which
should make test less flaky.
Closes #1036
> test/components/kubernetes: remove kubelet pod when testing node labels

- scripts/find-updates.sh
> scripts/find-update.sh: fix etcd current version

- docs/KEYS.md
> KEYS: Add knrt10 gpg key fingerprint

- pkg/platform/aks/aks.go
- pkg/platform/aks/template.go
> pkg/platform/aks: fix provisioning, update Kubernetes version and dependencies

- docs/development/README.md
- Add link to coding style guide.
- Make link text match the document title of updating-components.md.
- Remove period from link to updating-components.md.
> docs/development: Add link to coding style guide

- scripts/find-updates.sh
Regression from https://github.com/kinvolk/lokomotive/pull/824/
> scripts/find-updates.sh: Fix providers

- test/components/prometheus-operator/prometheus_operator_test.go
- test/components/util/util.go
This commit adds a code to verify if the PVCs in the prometheus-operator
component reach the Bound phase in the record time.
> e2e: Add test for prometheus-operator PVC

- docs/configuration-reference/components/headlamp.md
> docs: Fix headlamp attribute reference table

- .github/workflows/ci.yaml
- Makefile
- test/components/openebs-operator/openebs_operator_test.go
As part of CI and make CI faster, build, test, lint and codespell will
run as part of github action.
closes: #1054
> Add github actions

- docs/configuration-reference/components/openebs-operator.md
> docs: openebs-operator link fix

- assets/terraform-modules/dns/manual/versions.tf
- assets/terraform-modules/packet/flatcar-linux/kubernetes/versions.tf
- docs/quickstarts/aws.md
- docs/quickstarts/baremetal.md
- docs/quickstarts/packet.md
> Remove Terraform 0.12 references

- assets/charts/components/gangway/templates/ingress.yaml
closes: #1144
Tested update from the already created certificate.
> gangway: consistency in certificate name

- assets/charts/components/rook/Chart.yaml
- assets/charts/components/rook/templates/role.yaml
- assets/charts/components/rook/values.yaml
- pkg/components/rook-ceph/manifests.go
@surajssd Can you please review if I have updated the manifests `pkg/components/rook-ceph/manifests.go` correctly.
> rook: update rook to 1.4.6

- assets/charts/components/contour/Chart.yaml
- assets/charts/components/contour/crds/01-crds.yaml
- assets/charts/components/contour/templates/01-contour-config.yaml
- assets/charts/components/contour/templates/02-job-certgen.yaml
- assets/charts/components/contour/templates/02-rbac.yaml
- assets/charts/components/contour/templates/02-role-contour.yaml
- assets/charts/components/contour/values.yaml
Release Notes:
https://github.com/projectcontour/contour/releases/tag/v1.9.0
> contour: Update to v1.9.0

- test/ingress/packet_test/match_host_test.go
> test/ingress/packet_test: ensure Ingress has rules and Ingresses

- docs/how-to-guides/upgrade-bootstrap-kubelet.md
> docs/how-to-guides/upgrade-bootstrap-kubelet.md: add uncordon step

- assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/azure/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
For changelog, see:
https://github.com/kinvolk/bootkube/compare/v0.14.0-helm2...kinvolk:v0.14.0-helm3
Closes #1174
> Update bootkube to latest version

- assets/terraform-modules/aws/flatcar-linux/kubernetes/versions.tf
- assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/versions.tf
- assets/terraform-modules/azure/flatcar-linux/kubernetes/versions.tf
- assets/terraform-modules/azure/flatcar-linux/kubernetes/workers/versions.tf
- assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/versions.tf
- assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/versions.tf
- assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/workers/versions.tf
- assets/terraform-modules/packet/flatcar-linux/kubernetes/versions.tf
- assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/versions.tf
- scripts/find-updates.sh
> update ct Terraform provider to 0.7.1

- cli/cmd/cluster-apply.go
- cli/cmd/cluster/apply.go
- cli/cmd/cluster/cluster.go
- cli/cmd/cluster/component-apply.go
- cli/cmd/cluster/component-delete.go
- cli/cmd/cluster/health.go
- cli/cmd/cluster/utils.go
- docs/cli/lokoctl_cluster_apply.md
- docs/troubleshooting/_index.md
- docs/troubleshooting/recovering-from-removed-controlplane-chart-release-with-removed-assets-directory.md
- pkg/platform/aws/aws.go
- pkg/platform/baremetal/baremetal.go
- pkg/platform/packet/packet.go
- pkg/platform/platform.go
- pkg/platform/platform_test.go
See commit messages for more details.
Closes #916
> Fix adding worker pools with TLS bootstrap

- docs/how-to-guides/upgrade-bootstrap-kubelet.md
This commit adds a step to replace image with rkt based kubelet and
without.
> docs upgrade-kubelet: Add step with rkt kubelet

- assets/charts/control-plane/calico/crds/bgpconfigurations.yaml
- assets/charts/control-plane/calico/crds/bgppeers.yaml
- assets/charts/control-plane/calico/crds/blockaffinities.yaml
- assets/charts/control-plane/calico/crds/clusterinformations.yaml
- assets/charts/control-plane/calico/crds/felixconfigurations.yaml
- assets/charts/control-plane/calico/crds/globalnetworkpolicies.yaml
- assets/charts/control-plane/calico/crds/globalnetworksets.yaml
- assets/charts/control-plane/calico/crds/hostendpoints.yaml
- assets/charts/control-plane/calico/crds/ipamblocks.yaml
- assets/charts/control-plane/calico/crds/ipamconfigs.yaml
- assets/charts/control-plane/calico/crds/ipamhandles.yaml
- assets/charts/control-plane/calico/crds/ippools.yaml
- assets/charts/control-plane/calico/crds/kubecontrollersconfigurations.yaml
- assets/charts/control-plane/calico/crds/networkpolicies.yaml
- assets/charts/control-plane/calico/crds/networksets.yaml
- assets/charts/control-plane/calico/templates/calico-node.yaml
- assets/charts/control-plane/calico/values.yaml
- assets/terraform-modules/bootkube/variables.tf
- scripts/find-updates.sh
> Update Calico to v3.17.0

- assets/terraform-modules/azure/flatcar-linux/kubernetes/versions.tf
- assets/terraform-modules/azure/flatcar-linux/kubernetes/workers/versions.tf
- docs/configuration-reference/platforms/aks.md
- pkg/platform/aks/aks.go
- pkg/platform/aks/template.go
- Update taints format for worked pools to map(string).
- Update docs.
> AKS: Update provider azurerm to 2.41.0

- docs/how-to-guides/troubleshoot-openebs.md
We missed adding the bootstrap kubelet update. This PR adds that.
> troubleshoot-openebs docs: Add bootstrap kubelet upgrading steps

- Makefile
- assets/terraform-modules/aws/flatcar-linux/kubernetes/bootstrap-configs.tf
- assets/terraform-modules/aws/flatcar-linux/kubernetes/variables.tf
- assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/bootstrap-configs.tf
- assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/variables.tf
- assets/terraform-modules/bare-metal/flatcar-linux/kubernetes/bootstrap-configs.tf
- assets/terraform-modules/node/bootstrap-tokens.tf
- assets/terraform-modules/packet/flatcar-linux/kubernetes/bootstrap-configs.tf
- assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/bootstrap-configs.tf
- assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/workers.tf
- assets/terraform-modules/worker/main.tf
> Add 'terraform fmt' check and fix files formatting in assets

- ci/packet/packet-cluster.lokocfg.envsubst
- test/components/velero/velero_test.go
Install velero on Packet CI pipeline.
> velero: Add e2e tests

- assets/charts/components/web-ui/Chart.yaml
- assets/charts/components/web-ui/values.yaml
- pkg/components/web-ui/component_test.go
> web-ui: bump to 0.2.1

- scripts/find-updates.sh
This PR fixes few nuances of the script that gave bad results and overall makes it more reliable.
> Update the `find-updates.sh` script

- assets/charts/components/contour/Chart.yaml
- assets/charts/components/contour/crds/01-crds.yaml
- assets/charts/components/contour/dashboards/contour-proxy.json
- assets/charts/components/contour/templates/00-common.yaml
- assets/charts/components/contour/templates/01-contour-config.yaml
- assets/charts/components/contour/templates/02-job-certgen.yaml
- assets/charts/components/contour/templates/02-role-contour.yaml
- assets/charts/components/contour/templates/03-contour.yaml
- assets/charts/components/contour/templates/03-envoy.yaml
- assets/charts/components/contour/values.yaml
Release Notes:
https://github.com/projectcontour/contour/releases/tag/v1.13.1.
---
Update steps:
```
kubectl apply -f https://raw.githubusercontent.com/projectcontour/contour/release-1.13/examples/contour/01-crds.yaml
lokoctl component apply contour
```
> contour: Update to v1.13.0

- CHANGELOG.md
- docs/how-to-guides/certificate-rotation.md
- docs/installer/lokoctl.md
- pkg/version/version.go
> Release v0.8.0

- assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/azure/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/controller/templates/etcd.yaml.tmpl
- assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/packet/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- ci/aks/aks-cluster.lokocfg.envsubst
Release Notes: https://github.com/etcd-io/etcd/releases/tag/v3.4.16
> etcd: Update to v3.4.16

- assets/charts/components/rook-ceph/.helmignore
- assets/charts/components/rook-ceph/Chart.yaml
- assets/charts/components/rook-ceph/templates/ceph-cluster.yaml
- assets/charts/components/rook-ceph/templates/ceph-toolbox.yaml
- assets/charts/components/rook-ceph/templates/storage-class.yaml
- assets/charts/components/rook-ceph/values.yaml
- pkg/components/rook-ceph/component.go
- pkg/components/rook-ceph/component_test.go
- pkg/components/rook-ceph/manifests.go
Signed-off-by: Suraj Deshmukh <suraj@kinvolk.io>
Part of #1528 
Also look into https://github.com/kinvolk/lokomotive/pull/1557#issuecomment-908091304
> rook-ceph: Move to helm chart

- assets/charts/control-plane/kube-apiserver/Chart.yaml
- assets/charts/control-plane/kube-apiserver/values.yaml
- assets/charts/control-plane/kubelet/Chart.yaml
- assets/charts/control-plane/kubelet/container-image/Dockerfile
- assets/charts/control-plane/kubelet/container-image/README.md
- assets/charts/control-plane/kubelet/container-image/iscsiadm
- assets/charts/control-plane/kubelet/values.yaml
- assets/charts/control-plane/kubernetes/Chart.yaml
- assets/charts/control-plane/kubernetes/values.yaml
- assets/terraform-modules/aws/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/aws/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
- assets/terraform-modules/azure/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/azure/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
- assets/terraform-modules/bootkube/variables.tf
- assets/terraform-modules/controller/variables.tf
- assets/terraform-modules/equinixmetal/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/equinixmetal/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
- assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/google-cloud/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
- assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/cl/controller.yaml.tmpl
- assets/terraform-modules/kvm-libvirt/flatcar-linux/kubernetes/workers/cl/worker.yaml.tmpl
- assets/terraform-modules/node/variables.tf
- assets/terraform-modules/worker/variables.tf
- docs/how-to-guides/troubleshoot-openebs.md
- pkg/platform/aks/aks.go
Update AKS to 1.21.2
Update other platforms to 1.21.4
> Update k8s to 1.21.4
